### ISSUE TITLE
UEF T3 Juggernaut rear tread animates backwards

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#1]

**Comment by Nojoke185** [comment]
rear track looked ok to me - seemed the front tread that was going backwards

**Comment by aeoncleanse** [comment]
Yeah my bad, it's the front one.

**Comment by aeoncleanse** [comment]
Taken a look at how this works, I don't think I can fix this. We need someone with the tools and knowledge of manipulating models and/or animations in this file format.

**Comment by aeoncleanse** [comment]
23d75f23ffa3ca2e7f21cc6f5fb9157c1b44f80c
