### ISSUE TITLE
Cybran T1 bot (Hydra) has a dummy weapon with 0 DPS

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#10]
to recreate...

build a cybran T1 land fac
ensure display more unit stats is on in FA options/interface menu
hover over icon of unit in factory
note the unit shows a dummy wep (direct fire) with 0 DPS
![hydra](https://cloud.githubusercontent.com/assets/16309355/13260518/b818c202-da53-11e5-9afe-509973f324a8.JPG)

**Comment by aeoncleanse** [comment]
Looked into this when I refactored the weapon just now. It's used to control the bot's engagement range properly, so we can't get rid of it. Just a quirk of nature.
