### ISSUE TITLE
[Blackops] ACU upgrade icons not being found

### ISSUE THREAD

**Issue by nocaps** [aeoncleanse/Mods#106]
Some of the upgrade icons don't work, or work inconsistently. Often an upgrade will be displayed as a yellow square and on rollover will display correctly (????), or the miniature icon displayed over the acu portrait on the bottom left of the screen will be yellow (but the upgrade itself is often fine). May be unrelated, or even intended, but a lot of upgrades appear to have completely unrelated icons to what function they actually perform.

**Comment by aeoncleanse** [comment]
It's working perfectly for me... Can you post logs for a game in which you see this error please?
