### ISSUE TITLE
New method of displaying Unit LOD's (Level of Detail)

### ISSUE THREAD

**Issue by Uveso** [aeoncleanse/Mods#107]
I have closed issue #100 because i have a new way to calculate LOD settings.

Well, what are LOD settings ?
Inside the unit blueprint you can finde the lod settings inside the DISPLAY array:

``` LUA
    Display = {
        Mesh = {
            IconFadeInZoom = 130, -- Strategic Icons will be displayed from zoomlevel 130 to max zoom
            LODs = {
                { -- This is LOD Setting No.0
                    LODCutoff = 200, -- Display LOD-0 From Zoomlevel 0-200, over 200 we use LOD1
                    Scrolling = true,
                    ShaderName = 'Unit',
                },
                { -- This is LOD Setting No.1
                    AlbedoName = 'uel0401_lod1_albedo.dds', -- For LOD-1 we are using a low resulution Texture
                    LODCutoff = 600, -- Display LOD-1 From Zoomlevel 200-600
                    ShaderName = 'Unit',
                    SpecularName = 'uel0401_lod1_specteam.dds', -- For LOD-1 we are using a low resulution Shader
                },
            },
        },
    },

```

If we have a close look to the unit, LOD-0 Settings will be used with the highest texture and most complex Unit Model.

Now we are zooming out. If we reach a zoomlevel above 130, IconFadeInZoom = 130 will tell the game its time to display a strategig icon over the unit.

If we zoom out more and go over a zoomlevel of 200, LODCutoff = 200 from LOD-0 will stop displaying the unit with Highres Textures.
Now the unit will be displayed with LOD-1 Settings. Using Lowres Textures and a low detailed Model.

If we now zoom out over 600, LODCutoff = 600 from LOD-1 will stop displaying the unit. Now we only see the strategic icon.

My Idea:
First of all, we should set IconFadeInZoom for all units to 130, so all units show a strategic icon at the same zoom level.
Now we could stop displaying all units who where fully covered from the stretegic icons. This should make the game a little bit faster.
And LOD should be calculated by the size of the unit. We can see a big Tank way longer then a smal bot.
So, while zoming out, all units should disapear related to their size. (Looks way better and more realistic)

Low and Highres textures and Unit models are also affected. Even if Units only have LOD-0 and not LOD-1 Settings, this will work flawless.
And of course it's changing LODS of all activated units. Original, black ops and any other activated mod.

Maybe those calculations could be an extra for Black Ops.
- Because its unleashed :)
- It makes the game faster!
- It looks better!
- It removes all UI-Lag (well, not really^^)

If you use my unitdebugger, you can test it already.
The New LOD calculation can be found inside the blueprint.lua, last function.
It's activated all the time, just activate the debugmod.
http://faforever.uveso.de/forum/UvesoDebuggerV2.9.rar

What do you think ?

**Comment by aeoncleanse** [comment]
It's a good plan. We could test this out here, then move it main-game? Also,  I think some strategic icons should come in at different points. Walls, for example, should appear when closer. T1 PD and AA as well. Smaller stuff.

**Comment by Uveso** [comment]
Sounds good. I will make a PR this week, and we can take a deeper look at it.

**Comment by Uveso** [comment]
Just to remind myself:
Also possible to disable LOD-1 and run the units only with LOD-0. So we have always full texture resulution and full detailed units. Most gfx cards can handle this and cpu usage is ridiculous low.

In fact this will save lua-memory and make the gamesimspeed faster in the endgame.
Absurd, isn't it ? But memory is the last bottleneck if you have an fast cpu.
