### ISSUE TITLE
Crash Report 11/07/2016

### ISSUE THREAD

**Issue by ZephyrWarrior** [aeoncleanse/Mods#108]
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x006cbc63
    attempted to read memory at 0x00000000

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1649.81 /deviation 328.703 /country CA /init init_faf.lua /numgames 3 /nobugreport /savereplay gpgnet://localhost/4926832/ZephyrWarrior.SCFAreplay /gpgnet 127.0.0.1:54671

Callstack:
    Unknown symbol (address 0x006cbc63)
    Unknown symbol (address 0x006cb8f0)
    Unknown symbol (address 0x1d3fa53b)

Last 100 lines of log...

debug: Loading module '\000/units/dra0202/dra0202_script.lua\000'
debug: Loading module '\000/units/ueb0202/ueb0202_script.lua\000'
debug: Loading module '\000/units/ueb1106/ueb1106_script.lua\000'
debug: Loading module '\000/units/xsa0102/xsa0102_script.lua\000'
debug: Loading module '\000/units/ual0205/ual0205_script.lua\000'
debug: Loading module '\000/projectiles/sdfheavyphasicautogun01/sdfheavyphasicautogun01_script.lua\000'
debug: Loading module '\000/units/ura0204/ura0204_script.lua\000'
debug: Loading module '\000/projectiles/cdflaserdisintegrator01/cdflaserdisintegrator01_script.lua\000'
warning: Error resolving cue 'XSL0001_Capture_Start' in bank 'XSL'
debug: Loading module '\000/units/uea0203/uea0203_script.lua\000'
debug: Loading module '\000/units/ual0309/ual0309_script.lua\000'
debug: Loading module '\000/units/ueb1201/ueb1201_script.lua\000'
debug: Loading module '\000/units/urb1106/urb1106_script.lua\000'
debug: Loading module '\000/units/uel0203/uel0203_script.lua\000'
debug: Loading module '\000/units/url0205/url0205_script.lua\000'
debug: Loading module '\000/units/ura0203/ura0203_script.lua\000'
debug: Loading module '\000/units/urb1302/urb1302_script.lua\000'
debug: Loading module '\000/units/dea0202/dea0202_script.lua\000'
debug: Loading module '\000/units/ueb4202/ueb4202_script.lua\000'
debug: Loading module '\000/units/xsb4202/xsb4202_script.lua\000'
debug: Loading module '\000/mods/blackopsunleashed/units/bab5102/bab5102_script.lua\000'
debug: Loading module '\000/units/del0204/del0204_script.lua\000'
debug: Loading module '\000/units/uel0111/uel0111_script.lua\000'
debug: Loading module '\000/projectiles/tifmissilecruise04/tifmissilecruise04_script.lua\000'
debug: Loading module '\000/units/uea0104/uea0104_script.lua\000'
debug: Loading module '\000/units/ueb4201/ueb4201_script.lua\000'
debug: Loading module '\000/units/uab1302/uab1302_script.lua\000'
debug: Loading module '\000/units/uel0205/uel0205_script.lua\000'
debug: Loading module '\000/projectiles/tifnapalmcarpetbomb02/tifnapalmcarpetbomb02_script.lua\000'
debug: Loading module '\000/units/xrb0104/xrb0104_script.lua\000'
debug: Loading module '\000/units/uab1201/uab1201_script.lua\000'
debug: Loading module '\000/projectiles/tdfriot01/tdfriot01_script.lua\000'
debug: Loading module '\000/units/uel0202/uel0202_script.lua\000'
debug: Loading module '\000/units/ueb5202/ueb5202_script.lua\000'
debug: Loading module '\000/units/xab1401/xab1401_script.lua\000'
debug: Loading module '\000/units/ueb2205/ueb2205_script.lua\000'
debug: Loading module '\000/units/ueb2109/ueb2109_script.lua\000'
debug: Loading module '\000/units/xsl0309/xsl0309_script.lua\000'
debug: Loading module '\000/units/drl0204/drl0204_script.lua\000'
debug: Loading module '\000/projectiles/cifcorsairmissile01/cifcorsairmissile01_script.lua\000'
debug: Loading module '\000/effects/entities/debrisboneattachlow01/debrisboneattachlow01_script.lua\000'
debug: Loading module '\000/units/urb0301/urb0301_script.lua\000'
debug: Loading module '\000/projectiles/cdfrocketiridium01/cdfrocketiridium01_script.lua\000'
debug: Loading module '\000/mods/blackopsunleashed/units/bab1106/bab1106_script.lua\000'
debug: Loading module '\000/projectiles/caaautocannon01/caaautocannon01_script.lua\000'
debug: Loading module '\000/units/ual0106/ual0106_script.lua\000'
debug: Loading module '\000/units/ues0201/ues0201_script.lua\000'
debug: Loading module '\000/units/ueb1302/ueb1302_script.lua\000'
debug: Loading module '\000/projectiles/caaburstcloud01/caaburstcloud01_script.lua\000'
debug: Loading module '\000/units/url0306/url0306_script.lua\000'
debug: Loading module '\000/projectiles/caananodart04/caananodart04_script.lua\000'
debug: Loading module '\000/units/xsb4301/xsb4301_script.lua\000'
debug: Loading module '\000/units/ueb0301/ueb0301_script.lua\000'
debug: Loading module '\000/units/url0111/url0111_script.lua\000'
debug: Loading module '\000/projectiles/cifneutronclusterbomb01/cifneutronclusterbomb01_script.lua\000'
debug: Loading module '\000/projectiles/cifneutronclusterbomb02/cifneutronclusterbomb02_script.lua\000'
debug: Loading module '\000/units/url0309/url0309_script.lua\000'
debug: Loading module '\000/units/xsb2304/xsb2304_script.lua\000'
debug: Loading module '\000/units/uel0307/uel0307_script.lua\000'
debug: Loading module '\000/units/uab3201/uab3201_script.lua\000'
debug: Loading module '\000/units/ueb2108/ueb2108_script.lua\000'
debug: Loading module '\000/projectiles/adfsonicpulsar01/adfsonicpulsar01_script.lua\000'
debug: Loading module '\000/projectiles/saalosaareautocannon04/saalosaareautocannon04_script.lua\000'
debug: Loading module '\000/units/url0303/url0303_script.lua\000'
debug: Loading module '\000/units/uel0309/uel0309_script.lua\000'
debug: Loading module '\000/mods/blackopsexunits/units/erl0301/erl0301_script.lua\000'
debug: Loading module '\000/mods/blackopsexunits/lua/exblackopsweapons.lua\000'
debug: Loading module '\000/mods/blackopsexunits/lua/exblackopsdefaultcollisionbeams.lua\000'
debug: Loading module '\000/mods/blackopsexunits/lua/exeffecttemplates.lua\000'
debug: Loading module '\000/mods/blackopsexunits/lua/exblackopseffecttemplates.lua\000'
debug: Loading module '\000/mods/blackopsexunits/lua/excollisionbeam.lua\000'
debug: Loading module '\000/units/uaa0103/uaa0103_script.lua\000'
debug: Loading module '\000/units/xrl0305/xrl0305_script.lua\000'
debug: Loading module '\000/units/ueb1301/ueb1301_script.lua\000'
debug: Loading module '\000/units/urb1301/urb1301_script.lua\000'
debug: Loading module '\000/mods/blackopsunleashed/units/bsb5205/bsb5205_script.lua\000'
debug: Loading module '\000/projectiles/tdfgauss01/tdfgauss01_script.lua\000'
debug: Loading module '\000/projectiles/aifbombgraviton01/aifbombgraviton01_script.lua\000'
debug: Loading module '\000/units/uab4302/uab4302_script.lua\000'
info: Hooked /units/uab4302/uab4302_script.lua with /mods/blackopsunleashed/hook/units/uab4302/uab4302_script.lua
debug: Loading module '\000/units/xsa0203/xsa0203_script.lua\000'
debug: Loading module '\000/projectiles/taamissileflayer02/taamissileflayer02_script.lua\000'
debug: Loading module '\000/mods/blackopsunleashed/units/bsa0002/bsa0002_script.lua\000'
debug: Loading module '\000/mods/blackopsunleashed/units/bsa0001/bsa0001_script.lua\000'
debug: Loading module '\000/units/uab1301/uab1301_script.lua\000'
debug: Loading module '\000/units/xsb4201/xsb4201_script.lua\000'
debug: Loading module '\000/projectiles/simantimissile01/simantimissile01_script.lua\000'
debug: Loading module '\000/units/xes0205/xes0205_script.lua\000'
debug: Loading module '\000/units/ueb4301/ueb4301_script.lua\000'
debug: Loading module '\000/units/ueb3104/ueb3104_script.lua\000'
debug: Loading module '\000/units/uel0303/uel0303_script.lua\000'
debug: Loading module '\000/units/urb2108/urb2108_script.lua\000'
debug: Loading module '\000/units/urb3104/urb3104_script.lua\000'
debug: Loading module '\000/projectiles/sdfheavyphasicautogun02/sdfheavyphasicautogun02_script.lua\000'
debug: Loading module '\000/projectiles/saalosaareautocannon01/saalosaareautocannon01_script.lua\000'
debug: Loading module '\000/units/ura0401/ura0401_script.lua\000'
debug: Loading module '\000/units/urb2304/urb2304_script.lua\000'
debug: Loading module '\000/units/uab2304/uab2304_script.lua\000'
debug: Loading module '\000/projectiles/aaazealotmissile01/aaazealotmissile01_script.lua\000'
debug: Loading module '\000/units/xeb2306/xeb2306_script.lua\000'

**Comment by AndroTritium** [comment]
Crashed when I was in-game with him.

**Comment by Uveso** [comment]
http://forums.faforever.com/viewtopic.php?f=3&t=12570

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x006cbc63 is caused by the Cybran unit "xrb0104" (Engineering Station - the Hive)

already fixed, (inside develop version) see:
https://github.com/FAForever/fa/pull/1375
