### ISSUE TITLE
Land factory unit order does not match default FAF

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#11]
Order of units in cybran factories does not match default FAF sort order

for example in blackops T2 factory sort order is
- engy
- rhino
- hoplite
- wagner
- banger
- etc

![image](https://cloud.githubusercontent.com/assets/16309355/13263557/edc7b080-da61-11e5-92d2-33d48e07cade.png)

default FAF order is:
- engy
- hoplite
- rhino
- wagner
- banger
- etc

![image](https://cloud.githubusercontent.com/assets/16309355/13263579/02ab8dc8-da62-11e5-938c-d6e7faac282b.png)

similar issue with T3 land units sort order (brick is before loyalist)
(This may just be a blackops thing I wasn't aware of!)
I have not checked the other factions so this may also apply to them

**Comment by aeoncleanse** [comment]
Far as I can tell this was done to group types of units together. I think it can be undone and reorganised, but do we want to? I kinda like having them in groups, given the extra complexity caused by so many new units.

**Comment by Nojoke185** [comment]
sounds like it is best to leave as is
it was more an observation than a proper issue
