### ISSUE TITLE
ACUs 1v1 weapons - all except UEF don't work properly.

### ISSUE THREAD

**Issue by MagHz** [aeoncleanse/Mods#111]
It's about the '1v1' weapons - gatling, maser and that Colossus beam for Aeon.
- UEF - gatling works, upgrades seem to work properly
- Aeon - beam 1 works (but is weak - maybe by design, but it's really low, like 150 dps?); any further upgrade doesn't change the damage (beam2 improves DPS by a bit, but it's due to increasing main weapon ROF to 2; beam3 is the same as beam2)
- Cybran - maser 1 works (but seems very weak, again around 100-150 dps); any further upgrades are broken like Aeon ones. Changing damage in `unit.bp` file doesn't change anything; also checked if I could change the range of the maser and set it to 120 - didn't change anything in-game.
- Seraphim - gatling doesn't work at all, not even visuals; DPS doesn't change at all. Additionally ACU uses gatling sound for normal weapon, even without the gatling upgrade.

'Artillery' upgrades seem to work properly (at least Sera and Aeon ones).

Also remember that torps in Seraphim didn't work at all, but that was maybe a week ago; might have been fixed since then, or might have been broken in other factions as well. Not sure about those.

Mod version - BOPS Unleashed + ACUs; current as of 2016-07-12, downloaded maybe 2h ago. No other mods installed aside from strategic icons. Game is pretty much freshly installed (Steam version).

supcom v3654
faf 0.11.60+577

**Comment by aeoncleanse** [comment]
The balance isn't being changed from BlackOps default. I've only looked into this for the Cybran, but stage 1 of the laser is indeed very weak. I'll look into the weapon damage not improving for upgrades.

**Comment by aeoncleanse** [comment]
Right. This fixes the Cybran laser upgrades. b62eeb5f574212a5b6de7ac6ab9dfaaabaca8362

**Comment by aeoncleanse** [comment]
483780faccf5eefc6d611e3f15c8becd5a859ed4 Fixes the Aeon one.

**Comment by aeoncleanse** [comment]
@MagHz This should be fixed. Please retest :)

**Comment by MagHz** [comment]
Yeah, all of it worked the last time I've tested. Thank you for your work!
