### ISSUE TITLE
Sera ACU - incorrect word use

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#112]
![image](https://cloud.githubusercontent.com/assets/16309355/16768045/6f2c2034-483a-11e6-9a9c-ed54ecdd517f.png)

see above pic
think the word usage is incorrect here - perhaps a small change required?
change to "over the course of.."?

**Comment by aeoncleanse** [comment]
c399f894e477c57906f8d00e54f506d83381466d
