### ISSUE TITLE
Sera ACU - log error on upgrade to plasma gattling cannon

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#113]
upgrade to plasma gattling cannon

leads to this log error:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 28159e30: ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(912): attempt to call method `ChangeMaxRadius' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(912): in function`CreateEnhancement'
            c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
            ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>

upgrade to second level (phased energy fields) shows this in log:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 29d4e6f0: ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(942): attempt to call method `AddDamageMod' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(942): in function`CreateEnhancement'
            c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
            ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>

upgrade to third level (secondary power feeds) shows this in log:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 27616bf0: ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(981): attempt to call method `AddDamageMod' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(981): in function`CreateEnhancement'
            c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
            ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>

**Comment by aeoncleanse** [comment]
0d389da12595e07f16187a141dcc8af55fca6c34
