### ISSUE TITLE
Sera ACU - advanced distortion algorithms

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#114]
after update to this enhancement, getting this in log when engaging enemy units:

WARNING: Error running lua script: ...orged alliance\mods\blackopsacus\lua\acusweapons.lua(217): access to nonexistent global variable "SDFSinnuntheWeapon"
         stack traceback:
            [C]: in function `error'
            ...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
            ...orged alliance\mods\blackopsacus\lua\acusweapons.lua(217): in function`PlayFxMuzzleChargeSequence'
            ...ramdata\faforever\bin\dev\lua\sim\defaultweapons.lua(640): in function <...ramdata\faforever\bin\dev\lua\sim\defaultweapons.lua:593>

**Comment by aeoncleanse** [comment]
ef8bc54ea03ade9f60c45700fa9a1c1905a0d0ed
