### ISSUE TITLE
Sera ACU - 2nd lambda update log error

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#116]
upgrade to 2nd lambda has following log issues:

2nd issue - upgrade should add 100 armor regen. Nothing is added

WARNING: Unable to find file /mods/blackopsacus/lua/blackopsdefaultantiprojectile.lua
WARNING: stack traceback:
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function`pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function`import'
WARNING:         ...e\mods\blackopsacus\units\esb0003\esb0003_script.lua(11): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function`pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [C]: in function`CreateUnit'
WARNING:         ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(263): in function `CreateLambdaUnit'
WARNING:         ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1039): in function`CreateEnhancement'
WARNING:         c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
WARNING:         ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/mods/blackopsacus/lua/blackopsdefaultantiprojectile.lua'
WARNING: stack traceback:
WARNING:         [C]: in function`error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function`import'
WARNING:         ...e\mods\blackopsacus\units\esb0003\esb0003_script.lua(11): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function`pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [C]: in function`CreateUnit'
WARNING:         ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(263): in function `CreateLambdaUnit'
WARNING:         ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1039): in function`CreateEnhancement'
WARNING:         c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
WARNING:         ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>
WARNING: Error importing /mods/blackopsacus/units/esb0003/esb0003_script.lua:
         Error importing '/mods/blackopsacus/units/esb0003/esb0003_script.lua'
         stack traceback:
            [C]: in function`error'
            ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
            [C]: in function`CreateUnit'
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(263): in function `CreateLambdaUnit'
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1039): in function`CreateEnhancement'
            c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
            ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>
INFO: Problems loading module '/mods/blackopsacus/units/esb0003/esb0003_script.lua'.  Falling back to 'Unit' in '/lua/sim/unit.lua'.
WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 50479530: ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(269): attempt to call method`SetParent' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(269): in function `CreateLambdaUnit'
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1039): in function`CreateEnhancement'
            c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
            ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>
WARNING: GetResource: Invalid name ""

**Comment by aeoncleanse** [comment]
6be394babd641ae7e78cff6770c38b49bde5d6f6
