### ISSUE TITLE
Sera ACU - improved combat systems

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#118]
upgrade to improved combat systems shows this error in log:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 2f0410f0: ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1207): attempt to call method `AddDamageMod' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1207): in function`CreateEnhancement'
            c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
            ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>

**Comment by aeoncleanse** [comment]
d13d645361737282de90ca69d67f2a93929bba75
