### ISSUE TITLE
Sera ACU - overcharge amplifier

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#120]
upgrade to overcharge amplifier shows this error in log:

2nd issue - additional 50 armor regen is not added

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 538e2a70: ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1285): attempt to call method `AddDamageMod' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\esl0001\esl0001_script.lua(1285): in function`CreateEnhancement'
            c:\programdata\faforever\bin\dev\lua\sim\unit.lua(3433): in function `OnWorkEnd'
            ...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua(80): in function <...data\faforever\bin\dev\lua\sim\tasks\enhancetask.lua:54>

**Comment by aeoncleanse** [comment]
71dac22e4832e5cf1ec816931e5e4da61af05ed6 

Try this now
