### ISSUE TITLE
Sera - Queries on quantum rift archway

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#122]
Queries on quantum rift archway…

Units produced from the rift have the following:

Property of “quantum power” does this bestow anything?
They drain 50 power always
Seem to be maxed out on health and are 5 star vet
ACU regen aura does not affect them (maybe the HP is at max when they emerge from the gate?)

The above may not be issues but wanted to put out for review

**Comment by aeoncleanse** [comment]
- No idea
- OK, probably something to do with the first
- Yes
- Interesting. Needs investigation.

**Comment by aeoncleanse** [comment]
@Uveso - The gateway seems to be missing an icon on the right hand side, you know where the ACUs and Engineers and Factories are listed. Think you can figure out why?

**Comment by Uveso** [comment]
This is caused in `controlgroups.lua` function `OnSelectionSetChanged` Line `121`

Some one forgot to impement global icon support there :)
All modded units wont be displayed there.

**Comment by aeoncleanse** [comment]
Icon is being fixed main game. Need to investigate how the Vet regen interacts with regen field.

**Comment by Uveso** [comment]
Bug:
If you build on all 3 rift facrories and you stop the build by pressing "s", only the main factory will stop. both drone factories continue with producing the last unit.

**Comment by aeoncleanse** [comment]
Ouch. I'm not sure there's a hook for "OnToldToStop"... :/ Trouble is the drones act like assisting factory units...

**Comment by aeoncleanse** [comment]
The regen aura thing is confirmed to be working properly now.

**Comment by aeoncleanse** [comment]
5e6319a139f999b5e1ae8e1972e4193a348b6f37
