### ISSUE TITLE
Sera ACU - advanced distortion algorithms - issues when firing

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#125]
Latest mod downloaded...

Sera ACU with advanced distortion algorithms
when firing weapon logs below:

INFO: Problems loading module '/mods/blackopsacus/projectiles/seraacubigball01/seraacubigball01_script.lua'.  Falling back to 'Projectile' in '/lua/sim/projectile.lua'.
WARNING: ...d alliance\mods\blackopsacus\lua\acusprojectiles.lua(563): access to nonexistent global variable "OmegaOverChargeProjectileTrails"
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
WARNING:         ...d alliance\mods\blackopsacus\lua\acusprojectiles.lua(563): in main chunk
WARNING:         [C]: in function`doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function`import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...ectiles\seraacubigball01\seraacubigball01_script.lua(9): in main chunk
WARNING:         [C]: in function`doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function`import'
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/mods/blackopsacus/lua/acusprojectiles.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function`import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...ectiles\seraacubigball01\seraacubigball01_script.lua(9): in main chunk
WARNING:         [C]: in function`doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function`import'
WARNING: Error importing /mods/blackopsacus/projectiles/seraacubigball01/seraacubigball01_script.lua:
         Error importing '/mods/blackopsacus/projectiles/seraacubigball01/seraacubigball01_script.lua'
         stack traceback:
            [C]: in function `error'
            ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function`import'
INFO: Problems loading module '/mods/blackopsacus/projectiles/seraacubigball01/seraacubigball01_script.lua'.  Falling back to 'Projectile' in '/lua/sim/projectile.lua'.

**Comment by Uveso** [comment]
looks like the same error like in #123 
Fixed in #130
