### ISSUE TITLE
UEF ACU - infinite billy nukes

### ISSUE THREAD

**Issue by MagHz** [aeoncleanse/Mods#127]
Fun stuff. If you've got the billy nuke upgrade it takes some time to build the first nuke, but once you fire it you don't need to build another one, as the nuke doesn't disappear and you can spam billys once every second or two. Good times, but probably shouldn't work like that.

Might also work like that for tac missiles, can't check right now.

**Comment by aeoncleanse** [comment]
Confirmed. For tacs as well. Well... That's wacky...

**Comment by aeoncleanse** [comment]
45d0dc0f2d5639b0cccca8141b5de9fe2f467b7f
