### ISSUE TITLE
Cybran T4 basalisk has 2 x head weapons with 0 DPS

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#13]
This may be by design but worth a mention?

![image](https://cloud.githubusercontent.com/assets/16309355/13270218/8bdb695c-da84-11e5-8158-30f979e516fe.png)

**Comment by Raistlfiren** [comment]
Yeah, there are two head weapons on the basilisk.

**Comment by aeoncleanse** [comment]
This is confirmed. They exist to facilitate other weapons, but are picked up the the UI code. Nothing we can do here. Thanks for commenting guys :)
