### ISSUE TITLE
Advanced ACU mod not working.

### ISSUE THREAD

**Issue by The137th** [aeoncleanse/Mods#139]
Hi 

The advanced ACU mod does not working in coop and is buggy in Skirmish.

In coop the game start with an empty map
In skirmish, the ACU is invisible and I cannot build anything.

![coop](https://cloud.githubusercontent.com/assets/20481016/16884840/97074096-4a99-11e6-9ba3-7923bb9e5ea7.jpg)

I turned off every other mod to make sure it is not due to conflict.
I also try with both the Blackops global support burron on/off
Yet the problem remains.

And yes I did download the latest version.

**Comment by Uveso** [comment]
Looks like the `right Mod` version, but the `wrong game` version.
I dont know if this is working in coop, but its working fine in skirmish and multiplayer.
Are you using game version 3652+ ?

**Comment by aeoncleanse** [comment]
Nothing I can do about coop. Coop is not intended to be modified, nor will BlackOps officially support it for the foreseeable future.

**Comment by The137th** [comment]
@Uveso 
I belive so. I've always allowed FAF to automatically update.
Unless there is something else I need to do?

@aeoncleanse 
But the thing is that Advanced ACU and BlackOps Used to work in coop as well as in Skirmish.

**Comment by aeoncleanse** [comment]
The game code has changed significantly, both in normal FAF and in COOP, in many cases in a divergent manner. We'll probably be able to make BlackOps work in COOP again in the future, but I don't know how much work it will be, so it's not on the release schedule for V10. 

Fastest way would be if you investigated why it doesn't work, fix the code, and make a PR with that fixed code so I can merge it in, The137th ;)

**Comment by aeoncleanse** [comment]
7e1f13dc1ffc30c24171432335f1e87fd8cfbbce
