### ISSUE TITLE
Cybran T4 basilisk toggle text is same

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#14]
when you press the toggle (change deployment mode) for the basilisk the toggle overlay text is the same both ways (mobile and static):

Transforms the unit into a stationary mode

**Comment by Raistlfiren** [comment]
I believe there is only one overlay text for everything. Maybe I am incorrect on this assumption, but I think this is true. If you toggle mass extractors on/off, they say the same phrase.

**Comment by aeoncleanse** [comment]
Fixed in 66f891768e0dfda71f0a04da425ce4f03d09fe57
