### ISSUE TITLE
AI never upgrades hydros

### ISSUE THREAD

**Issue by PlaYsiA** [aeoncleanse/Mods#146]
Not exactly a high priority, but as the title says, the AI doesn't seem to have support for upgrading the hydrocarbon plants.

**Comment by Uveso** [comment]
Yeah this is right.
Like plaatons for building units, there are also platoons for upgrading buildings. But only platoons for Buildings/ Units are imported (sorian AI scripts).
If we want the Ai to upgrade custom buildings, we have to add a way to import Upgrades like Build platoons stored inside the customunits folder.

At the moment i am not able to implement such a function without ruining the game ^^
Maybe there is a easier way with hooking (injecting) those platoons inside the game.

I will write this on my ToDo list.

**Comment by Uveso** [comment]
At the moment i have no time to go deeper inside the AI scripts.
So this will not be fixed in first release.

**Comment by Uveso** [comment]
This can be closed!

Ok i digged deep into the code to understand how massextractor ugrades work, and how i can use it to make hydro upgrades.

Units and buildings are upgraded from the function `UnitUpgradeAI` inside platoon.lua.

UnitUpgradeAI is called from `AIEconomyUpgradeBuilders.lua` with Buildergroups. This can be nondestructive hooked with adding a simple Array (BuilderGroup for Hydros).

But these Buildergroups are forming a platoon with templates from `Platoontemplates.lua`, `StructureTemplates.lua` and `upgradetemplates.lua`.
Bad thing is, i can't make a nondestructive hook here.
Templatearrays don't have an index and i need to copy the full array and add the hydros there.

Second problem are the BaseBuilderTemplates inside `ChallengeMain.lua`, `RushMainLand.lua` and `NormalMain.lua`.
They are also without index, and i need to copy the whole stuff here too.

And of course all corresponding sorianAI files also need to be changed.

To make this work we need to change about 40 (forty) AI files with destructive hooks.

hahaha No :)

**Comment by aeoncleanse** [comment]
hahaha No :) is a good response. Thanks mate :p

**Comment by Uveso** [comment]
@aeoncleanse 
There is an issue with missing AI scripts for T3 mobile land units: https://github.com/FAForever/fa/issues/2317
Maybe i can implement the Hydrocarbon scripts together with the T3 mobil AA stuff.
So the main game would be able to manage hydrocarbon plants!

What do you think ? Should i impement this into the maingame with the T3 AA scripts ?
