### ISSUE TITLE
Cybran T3 Cloak generator (shadow) - incorrect text

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#15]
Cybran T3 Cloak generator (shadow)
The text description for this unit seems to be missing a word and has a typo

![image](https://cloud.githubusercontent.com/assets/16309355/13270615/387054b4-da87-11e5-9e49-30f33832b2e2.png)
- typo word "anyting"
- seems to be missing the word "to" (invisible to visual sensors)

**Comment by aeoncleanse** [comment]
Fixed in b6632d1d0c9ed33b6ce49136f6b8d79aff38fcb9
