### ISSUE TITLE
ACU projectiles on FAF skirmish

### ISSUE THREAD

**Issue by ghost** [aeoncleanse/Mods#154]
When using the ACUs mod through the FAF client, I am finding that a lot of the projectiles from ACUs aren't working correctly - the UEF ACU's flamethrower's projectiles do not seem to move at all from the barrel, and the left arm cannon does not seem to fire anything on the Seraphim and Aeon ACUs even when upgraded for combat.

**Comment by aeoncleanse** [comment]
Logs please.

**Comment by ghost** [comment]
There we are - just loaded up a match as UEF, upgraded to level 1 combat engineering and level one cluster missiles - the missiles fired up and never came back down and the flamer projectiles didn't move.
[game.log.txt](https://github.com/aeoncleanse/Mods/files/419561/game.log.txt)
[forever.log.txt](https://github.com/aeoncleanse/Mods/files/419562/forever.log.txt)

**Comment by aeoncleanse** [comment]
thanks

**Comment by aeoncleanse** [comment]
Working fine my end. Looks like your game isn't loading the files correctly. Make sure you have the latest version downloaded and try again please.

**Comment by ghost** [comment]
Hrm I redownloaded it and tried again - same issues through FAF. I also tried it through the steam version of the game but the ACU's model would not appear (I've heard this is a game version issue though), and none of the icons for ACU upgrades would load through the steam version (icons loaded fine with your icon support mod enabled though). Would the fact that I'm running FAF through the steam version of Forged Alliance be causing issues perhaps? Thanks for the help!

**Comment by ghost** [comment]
I could try doing a full reinstall of the game.

**Comment by aeoncleanse** [comment]
I'm running it via a steam install too, so I doubt it :/

**Comment by ghost** [comment]
I tried doing a full reinstall of Forged Alliance - I deleted the appdata/local/gas powered games folder, the documents/my games/gas powered games, and the steamapps/common/supreme commander forged alliance folders, and also uninstalled FAF. I then reinstalled and added only your current versions of BlackOps Unleashed and BlackOps ACUs as well as BlackOps support 5.0. I then started a skirmish match and again the ACU would not spawn, and appeared to be trying to upgrade something, I used the alt-f2 spawn menu to spawn in another ACU which seemed to have all the upgrade models attached to it and started able to build tier 3 units. No projectiles would appear, even for vanilla units. A skirmish without any mods active worked just fine. Is it worth posting logs for this? Is there some dependency of BlackOps that I am missing?

**Comment by aeoncleanse** [comment]
BlackOps Support???

**Comment by ghost** [comment]
Your global icon support mod - none of the icons from BlackOps Unleashed or BlackOps ACUs would load on steam forged alliance without it.

**Comment by aeoncleanse** [comment]
Yes they will. GIS is no longer needed with this new version, as GIS functionality has been built into the default FAF code :)

**Comment by ghost** [comment]
Oh I was meaning directly through the steam version of Forged Alliance, not through FAF.

**Comment by aeoncleanse** [comment]
This mod will not work there. It's expressly designed for FAF V3652 and up.

**Comment by ghost** [comment]
Oh ok :) so do you have any ideas as to why it won't work on FAF?

**Comment by aeoncleanse** [comment]
Yes. The support mod isn't supposed to, so it doesn't. Please turn off BO Support, use the two mods with FAF, and report if the errors are gone for you.

**Comment by ghost** [comment]
That first log post was without Blackops support. I never used Blackops support with FAF.
