### ISSUE TITLE
Desync on start?

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#156]
Make sure this isn't a thing as of 3658 patch.

**Comment by Uveso** [comment]
I play this in LAN multiplayer every week. There is no desync in unnleashed or AACU. At least not with the FA develop version :) But i am almost 100% sure, BO is stable.

**Comment by aeoncleanse** [comment]
Same my end :/

**Comment by Uveso** [comment]
I had no desync the last 2 weeks.
Also not a single forum post or pm about it.
I think we can slowly close this :)
