### ISSUE TITLE
3 and 4 tiered acu upgrades problem

### ISSUE THREAD

**Issue by JaggedAppliance** [aeoncleanse/Mods#177]
If you click on the 3rd and final upgrade when you have none of the tiers of that upgrade completed, the first upgrade will not start and the second and third upgrade will be queued but also never start because the first never started either. 

This is the case with every 3 tiered acu upgrade. This also happens on the 3rd and 4th tier of the uef shield upgrades.

If you have completed all 3 tiers of an upgrade, you can click the first one again and start over. You get a warning that you will be removing an upgrade. 
[log.zip](https://github.com/aeoncleanse/Mods/files/440421/log.zip)

If you complete tier 1 and then try to click tier 3 or 4 you will be warned that you will remove an upgrade, and if you proceed you will lose your tier 1 upgrade and your acu will go idle.

**Comment by Nojoke185** [comment]
is this with the notify mod?
I believe that is only compatible with base FAF com upgrades and not the BO ones
if not then not sure what the problem is - over to icedreamer!

**Comment by Uveso** [comment]
```
warning: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 20de62f0: ...rever\gamedata\lua.nx4\lua\sim\tasks\enhancetask.lua(41): *ERROR: Ordered enhancement does not have the proper prereq!
         stack traceback:
            [C]: in function `error'
            ...gramdata\faforever\gamedata\lua.nx4\lua\sim\unit.lua(2526): in function `OnWorkBegin'
            ...rever\gamedata\lua.nx4\lua\sim\tasks\enhancetask.lua(41): in function <...rever\gamedata\lua.nx4\lua\sim\tasks\enhancetask.lua:33>
```

This error will show up, if you try to build an enhancement, but you don't have the prereq.
Means, if you try to start upgrade to Tier3, you need to have build Tier2 before (as prereq).

Normaly you can't klick on the Tier3 button if you dont have already build Tier2.

**Comment by aeoncleanse** [comment]
Are you meant to be able to click the top upgrade in the normal game? Is it meant to queue? If not, is the behaviour here different to normal?

**Comment by JaggedAppliance** [comment]
I'm playing so long with notify that i forgot all about it, notify was the problem here.
