### ISSUE TITLE
ACU mod multi-upgrade

### ISSUE THREAD

**Issue by PlaYsiA** [aeoncleanse/Mods#178]
When you try and do a T2-T4 upgrade on your ACU, ie: click the t4 engineering upgrade on an unupgraded ACU, it wont work.

This one is really easy to check, just start a game and click T4 gun or a t3 back upgrade and watch what happens (or doesn't).

**Comment by Uveso** [comment]
Those icons are greyed out, right ? You only can click highlighted icons.
We add the ability to show the tooltip also on greyed out icons, this don't mean you can click them :)

**Comment by PlaYsiA** [comment]
They are not greyed out.

![untitled](https://cloud.githubusercontent.com/assets/20159802/18034257/cccdcbb4-6d7b-11e6-9d15-839f5b499045.jpg)

**Comment by aeoncleanse** [comment]
![image](https://cloud.githubusercontent.com/assets/8494967/18034642/cb0177b4-6d39-11e6-983b-1a71ea7f62ca.png)

Whatever's going on, your game is not loading the mod correctly. Please make sure you're using the latest mod alongside the FAF BETA.

**Comment by Uveso** [comment]
The mod "Notify" is causing this.

`uid = "5048d937-4872-4e86-9f09-dd1806a0629c"`
in case you want to add Notify to the `conflicts` list inside mod_info.lua

[edit] Notify on github:
https://github.com/CodingSquirrel/Notify

**Comment by PlaYsiA** [comment]
Definitely notify
