### ISSUE TITLE
Artemis Controller Structure Death OP[BlackOps]

### ISSUE THREAD

**Issue by ArchAngel075** [aeoncleanse/Mods#181]
I built an Aeon Artemis (Experimental sat), After fooling with friends and having the Artemis control center destroyed the Artemis continued to function happily, while the UEF Experimental sat functioned properly (on controller death the sat itself died too)
Not sure if its a bug as the Artemis description states that should the controller die the Artemis as-well will die.

In Short, on controller death the Artemis sat was able to still wreck havoc as-if its controller was alive.

Remember this occurred on friendly fire, not sure if it changes anything.

**Comment by aeoncleanse** [comment]
Yeah this is a bug
