### ISSUE TITLE
Possible issue, Aeon Purifier T3 TML

### ISSUE THREAD

**Issue by PlaYsiA** [aeoncleanse/Mods#188]
iirc the t3 tml showed an area of effect when you choose to launch somewhere. Came up in one of my LAN games yesterday.

I could be wrong.

**Comment by aeoncleanse** [comment]
If it does, I think that would be correct. Normal TMLs do as well I think.

**Comment by PlaYsiA** [comment]
Confirmed just then that normal TMLs show an aoe indicator as well.

**Comment by PlaYsiA** [comment]
Yo, this is still a problem. It should show an aoe.

**Comment by aeoncleanse** [comment]
206a1380a42625121ef2798ba693434d29b9c423
