### ISSUE TITLE
T3 Sera Gunship Weird LOS/Radar values

### ISSUE THREAD

**Issue by PlaYsiA** [aeoncleanse/Mods#189]
Check the attached file. The gunship has a huge sight range, then is the gun range, followed by the radar range being smallest. If you check all the other t3 gunships the radar always has the biggest range.

This has probably been an oversight for a long time. Solution: probably swap sight and radar to match other t3 gunships?

![untitled](https://cloud.githubusercontent.com/assets/20159802/18417816/a364ea0c-787d-11e6-998f-5cd012c73f69.png)

**Comment by aeoncleanse** [comment]
Sounds like a plan to me. Make a PR?  ;)

**Comment by PlaYsiA** [comment]
Not really sure how to actually make the changes :(

It's here:
\BlackOpsUnleashed\units\BSA0310\BSA0310_unit.bp

Intel = {
        VisionRadius = 32,
    },

I'm pretty sure the radar value should be in there but it's not :(

Wait maybe it doesn't have radar at all and it's the second weapon using the radar overlay or something?

**Comment by aeoncleanse** [comment]
That's not a Radar circle at all, it's AA.

**Comment by PlaYsiA** [comment]
Well there we go, "problem" solved
