### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#19]
The icon search code throws errors because it can't find a whole slew of unit icons are game start. The icons are not present, need to source them from somewhere.

**Comment by aeoncleanse** [comment]
BAB0001
BAB0003
BAB0004
BEB0001
BEB0003
BEB0004
BEL9010
BRB0005
BRB0006
BRB0007
BSB0002
BSB0003
BSB0006
BSL0403
BSL0404

**Comment by Uveso** [comment]
These units don't need an icon, there are not build by the user.
All units are a child from a parent Unit.

BAB0001 Cybran Anti-Teleport Emitter (unused Unit, folder units/BAB0001 can be deleted)
BRB0005 AA Laser Emitter (unused Unit, folder units/BRB0005 can be deleted)
BSL0403 Seraphim Unidentified Residual Energy Signature (unused Unit, folder units/BSL0403 can be deleted)

BAB0003 Cybran Anti-Teleport Emitter (created from bab4309 Anti-Teleport Generator)
BAB0004 Cybran Anti-Teleport Emitter (created from bab4209 Anti-Teleport Generator)
BEB0001 UEF Air Staging Facility (Landingpads for the bea0402 Experimental Aerial Fortress)
BEB0003 UEF Anti-Teleport Emitter (created from beb4309 Anti-Teleport Field Tower)
BEB0004 UEF Anti-Teleport Emitter (created from beb4209 Anti-Teleport Field Tower)
BEL9010 Seraphim civilian Jammer Crystal (created from bel0402 Experimental Assault Bot(SpoofingThread))
BRB0006 Cybran Anti-Teleport Emitter (created from brb4309 Anti-Teleport Tower)
BRB0007 Cybran Anti-Teleport Emitter (created from brb4209 Anti-Teleport Tower)
BSB0002 Seraphim Factory (created by bss2402 Seraphim Quantum Rift Archway)
BSB0003 Seraphim Anti-Teleport Emitter (created by bsb4309 Anti-Teleport Tower)
BSB0006 Seraphim Anti-Teleport Emitter (created by bsb4209 Anti-Teleport Tower)
BSL0404 Seraphim Unidentified Residual Energy Signature (created from SDFSinnuntheWeapon01)

**Comment by aeoncleanse** [comment]
Sorry yup, found that out later. Might make placeholders to just shut up the warning.

**Comment by aeoncleanse** [comment]
e489f37ed27243104ac7eb85fc2a0122009bd03c
