### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by RavenCurow** [aeoncleanse/Mods#190]
Blackops ACUs
Aeon commander has typo in bp.general. TechLevel = 'RULEUTL_perimental', instead of TechLevel = 'RULEUTL_Experimental',

Blackops Unleashed.
BAA0001 shows as not having a category type in error log.
BRB0004 does not have a tech category in error log
BEB0001 missing category type in error log.

**Comment by Uveso** [comment]
i put this in a single PR
https://github.com/aeoncleanse/Mods/pull/192

[edit] thank's for reporting :)

**Comment by Uveso** [comment]
Hello RavenCurow,
The PR for this has been merged. you can close this issue now ;)

**Comment by Uveso** [comment]
THAT was fast! Thanks a lot RavenCurow :D
