### ISSUE TITLE
Investigate gameplay re. Satellites and SMD and rebuilding.

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#193]

**Comment by Uveso** [comment]
I found the post.
http://forums.faforever.com/viewtopic.php?f=31&t=13008&start=40#p135622

```
Is it possible to rebuild the UEF T2 Spy Satellite (Hawkeye)? If no, why? If yes, how?
It can be shot down by Strategic Missile Defense, but it can't be rebuilt. This seems a little silly.
```

Well it was not the novax sat :)
I tested this and the nukedense is indeed attacking and killing the spy sat from the uef commander.
You can't rebuild the sat directly. You can downgrade the enhancement and then upgrade to spy sat again.

PR is on the way.
