### ISSUE TITLE
Old Blackops Mods in Vault

### ISSUE THREAD

**Issue by PlaYsiA** [aeoncleanse/Mods#195]
Remove them. I keep having to explain to people in #aeolus that they don't work.

I'm not always online to do this, how many people are confused or just quit faf because of this? They don't work and it's dumb to leave them up.

**Comment by PlaYsiA** [comment]
I have commented some of them. But this is not a real fix.

**Comment by aeoncleanse** [comment]
Old mods are now hidden.
