### ISSUE TITLE
Audio Engine Setup

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#20]
Need to find a way to push the soundbanks to a readable location in gamedata, or find the lua responsible for tracking down and integrating such files.

**Comment by Uveso** [comment]
what do you need exactly ?

if u want to show the blueprint data from Audio;
the last point to check a sound is in Unit.lua @ PlayUnitSound = function(self, sound)
the first point where i check this is the Blueprint.lua inside the ACU Mod.

but if u want to check, if an sound exist in the wavebank, you have to play the sound and watch the error log.

if u are interested, i have started to programm an unitdebugger. its far from finished, but it can play all Unitsounds to check if there are working.
it also checks uniticons, techlevel etc. And it creates scripts for the sorian AI Customunits folder.

**Comment by aeoncleanse** [comment]
I need the mod to be able to see the sound file in the first place. Sound files currently need to be placed manually in the gamedata folder, they don't work with a normal download mod.

**Comment by Uveso** [comment]
ok you need the mod to see soundfiles ?
This funktion shows all Soundfiles ind Gamedir/sounds:

``` LUA
function CheckSoundbank()
    LOG('Archivar Debugger: - CheckSound')
    for k,file in DiskFindFiles('/sounds/', '*.*') do
        if file == "/sounds/blackopssb.xsb" then
            LOG('Black Ops Soundbank found!')
        end
        if file == "/sounds/blackopswb.xwb" then
            LOG('Black Ops Wavebank found!')
        end
    end
end
```

if you mean with "see" - the game should see the sounds of the mod, inside the modfolder:
Add to the "init_BlackOps.lua":

``` LUA
mount_dir(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods\\BlackOpsUnleashed\\sounds', '/sounds')
```

**Comment by Uveso** [comment]
Could be nice if the game always use the sound inside the modfolders, if a mod has sounds.
If u add this function to the init_*.lua, the game will use the modsounds inside the modfolders.
Testet with black ops and TotalMayhem.

```LUA
function mount_ModSounds()
	MODFOLDER = SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods\\'
	LOG('mount_ModSounds: Start')
	for mid,moddir in io.dir( MODFOLDER..'*.*') do
		if moddir != '.' and moddir != '..' then
			LOG('mount_ModSounds: found mod:'..moddir..'')
			for sid,sounds in io.dir(MODFOLDER..moddir..'\\sounds\\*.*') do
				if sounds != '.' and sounds != '..' then
					LOG('mount_ModSounds: found sound: '..sounds..'. Mounting sound directory')
						mount_dir(MODFOLDER..moddir..'\\sounds', '/sounds')
					break
				end
			end
		end
	end
end
mount_ModSounds()

```

**Comment by Uveso** [comment]
Maybe it would be nice, if the Game always use the sound inside the modfolders of all mods.
if u add this function to the/all init_*.lua files, the game will use /sounds/ inside all modfolders.

``` LUA
function mount_ModSounds()
    MODFOLDER = SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods\\'
    LOG('mount_ModSounds: Start')
    for mid,moddir in io.dir( MODFOLDER..'*.*') do
        if moddir != '.' and moddir != '..' then
            LOG('mount_ModSounds: found mod:'..moddir..'')
            for sid,sounds in io.dir(MODFOLDER..moddir..'\\sounds\\*.*') do
                if sounds != '.' and sounds != '..' then
                    LOG('mount_ModSounds: found sound: '..sounds..'. Mounting sound directory')
                    mount_dir(MODFOLDER..moddir..'\\sounds', '/sounds')
                    break
                end
            end
        end
    end
end
mount_ModSounds()
```

**Comment by aeoncleanse** [comment]
That first bit is the kind of thing. We want to do this outside of the init files to take account of people with different folder paths etc. Where in the lua is CheckSoundbank() ?

**Comment by Uveso** [comment]
Different folder path ? It is the same way like mods and maps are mounted. if the user has installed the mod where the game can find it, the sound also will be found ?!?
(I was already trying to get the sounds from inside a mod. no way)

Are you sure there is a  CheckSoundbank() command ? 
i know 3 commands defined inside game lua scripts:

```
Unit.lua PlayUnitSound('Killed')
Unit.lua PlayUnitAmbientSound( 'ConstructLoop' )
Unit.lua StopUnitAmbientSound( 'ConstructLoop' )
```

All other soundcommands are internal (inside ForgedAlliance.exe):

```
sound = Sound{ Bank = 'XGG', Cue = 'Computer_Computer_MissileLaunch_01351' }

cue,bank = GetCueBank(sound)

PlaySound(sound)
StopSound(sound)

SetAmbientSound( bp[sound], bp.Audio['AmbientRumble'] )
PlayVoice(Sound{Bank = 'XGG',Cue = 'XGG_Computer__04716'}, true)

EnableWorldSounds()
DisableWorldSounds()
PauseSound("World",true)
StopAllSounds()
```

[Edit:]
Loading sounds are handled by the ForgedAlliance.exe at gamestart, way before any mod is loaded. I dont see a way to get the sounds from Mod-Lua side. But as always, maybe i am wrong :)

**Comment by aeoncleanse** [comment]
Sorry, that function was one you just made up, kk. Looks like we will have to use the init files after all :(

**Comment by Uveso** [comment]
i tried some ideas last night, but i don't found a better solution :/

**Comment by Uveso** [comment]
Hello icedreamer,

is it possible to add the mount_ModSounds function to the file "init_fafbeta.lua" ?
I am finished with the Total Mayhem update and need the change, so i can upload the Mod to the vault.

Here is a copy+paste ready version: (i added it at the end of the file init_fafbeta.lua)

``` LUA
function mount_ModSounds(MODFOLDER)
    for mid,moddir in io.dir( MODFOLDER..'\\*.*') do
        if moddir != '.' and moddir != '..' then
            for sid,sounds in io.dir(MODFOLDER..'\\'..moddir..'\\sounds\\*.*') do
                if sounds != '.' and sounds != '..' then
                    LOG('mount_ModSounds: found sound directory inside mod: '..moddir..'. Mounting sound directory...')
                        mount_dir(MODFOLDER..'\\'..moddir..'\\sounds', '/sounds')
                    break
                end
            end
        end
    end
end
-- these are the classic supcom directories. They don't work with accents or other foreign characters in usernames
mount_ModSounds(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods')
-- these are the local FAF directories. The My Games ones are only there for people with usernames that don't work in the uppder ones.
mount_ModSounds(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods')
```

Btw, Awesome work on the ACU's :)

greetings Uveso.

**Comment by Sheeo** [comment]
Hey Uveso, nice job on this.

Only issue is that installed mods will then always have their sounds mounted, even if they aren't enabled. There's also no 'clean' way to override/overwrite sounds, especially not if other mods also modify them.

We should make this clear in documentation and potentially special case these mods in the client -- so there's an easy way to figure out which 'sound mods' you have installed.

**Comment by Uveso** [comment]
Hello Sheeo,

i think, this is not a problem.
If u don't mount the /mod/sound directory, the user has to copy the sound to the Game/sound dir.
This way the sound will also be mounted always. It makes no difference.

And sounds are only mounted from the game, not loaded. They only will be loaded once, if the sounds is actually played. It dont use memory, if u dont play it.
i Know the log says like "SND: Loaded WaveBank 'aeonselect' at 2f46030". But its not loaded, its only indexed.

You said "a clean way to overwrite sounds" ?
If a mod don't use the original filename of an existing soundfile, it won't be overwrite any sound.
Do you know a mod, that is overwriting existing files ?
(BlackOps and TotalMayhem dont overwrite existing soundfiles)
If so, we can simply add a sound-file-blacklist and check, if a mod/sound dir is containing any of the original files, and if so we simply don't mount it.

in this case, here is an updated script with blacklisting the original soundfiles. Just to be sure we dont break any sounds:

``` LUA
-- START mount_ModSounds function -----------------------------------------------------
local SoundFileBlackList = {
aeonselect=true,
ambienttest=true,
cybranselect=true,
explosions=true,
explosionsstream=true,
fmv_bg=true,
impacts=true,
interface=true,
music=true,
op_briefing=true,
seraphimselect=true,
uaa=true,
uaadestroy=true,
uaaweapon=true,
uab=true,
ual=true,
ualdestroy=true,
ualweapon=true,
uas=true,
uasdestroy=true,
uasweapon=true,
uea=true,
ueadestroy=true,
ueaweapon=true,
ueb=true,
uefselect=true,
uel=true,
ueldestroy=true,
uelweapon=true,
ues=true,
uesdestroy=true,
uesweapon=true,
unitrumble=true,
unitsglobal=true,
ura=true,
uradestroy=true,
uraweapon=true,
urb=true,
url=true,
urldestroy=true,
urlweapon=true,
urs=true,
ursdestroy=true,
ursstream=true,
ursweapon=true,
xaa_weapon=true,
xab=true,
xal=true,
xal_weapon=true,
xas=true,
xas_weapons=true,
xea=true,
xea_weapons=true,
xeb=true,
xel=true,
xel_weapons=true,
xes=true,
xes_destroy=true,
xes_weapons=true,
xra=true,
xra_weapon=true,
xrb=true,
xrl=true,
xrl_stream=true,
xrl_weapon=true,
xrs=true,
xrs_weapon=true,
xsa=true,
xsa_destroy=true,
xsa_weapon=true,
xsb=true,
xsb_weapon=true,
xsl=true,
xsl_destroy=true,
xsl_weapon=true,
xss=true,
xss_destroy=true,
xss_weapon=true,
briefings=true,
seraphim_language=true,
x01_vo=true,
x02_vo=true,
x03_vo=true,
x04_vo=true,
x05_vo=true,
x06_vo=true,
x1t_vo=true,
x_fmv=true,
xgg=true,
}
function mount_ModSounds(MODFOLDER)
    for mid,moddir in io.dir( MODFOLDER..'\\*.*') do
        if moddir != '.' and moddir != '..' then
            FoundBlacklistedSound = false
            FoundSound = false
            for sid,sounds in io.dir(MODFOLDER..'\\'..moddir..'\\sounds\\*.*') do
                if sounds != '.' and sounds != '..' then
                    FoundSound = true
                    if SoundFileBlackList[string.lower(string.sub(sounds, 1 , string.find(sounds, '[%.]')-1))] and not FoundBlacklistedSound then -- removing filename extension and then compare with blacklist
                        LOG('mount_ModSounds: found blacklisted sound inside mod: '..moddir..'. Mounting sound aborted.')
                        FoundBlacklistedSound = true
                    end
                end
            end
            if FoundSound and not FoundBlacklistedSound then
                LOG('mount_ModSounds: found sound directory inside mod: '..moddir..'. Mounting sound directory...')
                mount_dir(MODFOLDER..'\\'..moddir..'\\sounds', '/sounds')
            end
        end
    end
end
-- these are the classic supcom directories. They don't work with accents or other foreign characters in usernames
mount_ModSounds(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods')
-- these are the local FAF directories. The My Games ones are only there for people with usernames that don't work in the uppder ones.
mount_ModSounds(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods')
-- END mount_ModSounds function -----------------------------------------------------
```

**Comment by aeoncleanse** [comment]
Finally got around to testing this...  It didn't work :/ 

Error on  Artemis Satellite - WARNING: Error resolving bank 'BlackOpsSB' to audio engine

To confirm, the log showed that the correct section of your code was entered. It _should_ have been mounted. 

To test any future changes, just spawn an Artemis Satellite (It's under T1 Air, Aeon in the cheats menu for some reason) and ground fire.

**Comment by Uveso** [comment]
Hello icedreamer,

i have a screensoot showing how it runs:
[http://faforever.uveso.de/forum/soundloading.png](http://faforever.uveso.de/forum/soundloading.png)
It is also proving, that sound only loaded, if they are played :)

To test sounds i am using my own debugger-mod. It can play all sounds from units.

As you can see on the screensoot, the sound is loaded from path

```
C:\Users\Hismoom\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\Mods\BlackOpsUnleashed\sounds\BlackOpsWB.xwb
```

I tested it on 3 PC's. (runing for weeks now without error)

But i have a guess. Maybe your BO soundbank is corrupt.
Here a working BO soundbank:
[http:/faforever.uveso.de/forum/BOsoundbank.zip](http:/faforever.uveso.de/forum/BOsoundbank.zip)

and just in case i changed something to the artemis sound, this is my Audioarray from baa0401

``` LUA
    Audio = {
        AirUnitWaterImpact = Sound {
            Bank = 'Explosions',
            Cue = 'Expl_Water_Lrg_01',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        AmbientMove = Sound {
            Bank = 'UAA',
            Cue = 'UAA0310_Move_Loop',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        Destroyed = Sound {
            Bank = 'UAADestroy',
            Cue = 'UAA_Destroy_Air',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        Destroyed2 = Sound {
            Bank = 'UALDestroy',
            Cue = 'UAL0401_Destroy',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        Killed = Sound {
            Bank = 'UAADestroy',
            Cue = 'UAA_Destroy_Air_Killed',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        StartMove = Sound {
            Bank = 'UAA',
            Cue = 'UAA0310_Move_Start',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        StopMove = Sound {
            Bank = 'UAA',
            Cue = 'UAA0310_Move_Stop',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        Thruster = Sound {
            Bank = 'UAA',
            Cue = 'UAA0310_Move_Thruster',
            LodCutoff = 'UnitMove_LodCutoff',
        },
        UISelection = Sound {
            Bank = 'Interface',
            Cue = 'Aeon_Select_Air',
            LodCutoff = 'UnitMove_LodCutoff',
        },
    },
```

greetings Uveso.

**Comment by Uveso** [comment]
Well forgot the audio array from baa0401:

``` LUA
-- Weapon: Golden Retribution
            Audio = {
                Fire = Sound {
                    Bank = 'BlackOpsSB',
                    Cue = 'artemis_fire_01',
                    LodCutoff = 'Weapon_LodCutoff',
                },
            },

--Weapon: Experimental Beam
            Audio = {
                BeamLoop = Sound {
                    Bank = 'UALWeapon',
                    Cue = 'UAL0401_Phason_Laser_Loop',
                    LodCutoff = 'Weapon_LodCutoff',
                },
                BeamStart = Sound {
                    Bank = 'UALWeapon',
                    Cue = 'UAL0401_Phason_Laser_Fire',
                    LodCutoff = 'Weapon_LodCutoff',
                },
                BeamStop = Sound {
                    Bank = 'UALWeapon',
                    Cue = 'UAL0401_Phason_Laser_Stop',
                    LodCutoff = 'Weapon_LodCutoff',
                },
                RackSalvoCharge  = Sound {
                    Bank = 'UALWeapon',
                    Cue = 'UAL0401_Phason_Laser_Charge',
                    LodCutoff = 'Weapon_LodCutoff',
                },
            },
```

artemis_fire_01 (first array)  is working here.

**Comment by aeoncleanse** [comment]
The guilty party was a corrupted set of sound files. Thanks for the download :)

@sheeo - I have tested this thoroughly with the BlackOps mod on top of 3654. I request that we amend the init file with this code alongside the 3654 patch launch.

**Comment by aeoncleanse** [comment]
e38e86a94e191d15f02e2f66393bf47d3ca70b7d
