### ISSUE TITLE
BlackOPS ACU not visible

### ISSUE THREAD

**Issue by truff63** [aeoncleanse/Mods#200]
Well, I downloaded the latest blackops mods {name = "BlackOps FAF: ACUs"  uid = "9e8ea941-c306-4751-b367-a00000010000"  version = 10} and moved them to my mods folder after removing the previous version. when i test i do not have a visible ACU when I zoom in. didnt test much past that. when i use the version from approx 9/14/2016 {uid = "9e8ea941-c306-4751-b367-e00000000305" version = 10} the acu is visible.

FAF launched game showing version 3659 in the upper left corner of the host game configuration window.

**Comment by aeoncleanse** [comment]
Use FAF Beta. This won't be a problem with the imminent 3660 release.
