### ISSUE TITLE
Model missing for BlackOps Acu Unleashed

### ISSUE THREAD

**Issue by neosapian6** [aeoncleanse/Mods#202]
recently installed and used the blackops mod (no sound in recording but they are working)
the only issue im having is the fact that i cannot physically see the model for my commander, the upgrades and icons show up, he can construct structures, and can use said upgrades, however the physical model for the commander is missing entirely.
the file type my recording program saved in wasnt apparently applicable so i  placed it into a zip file for you to view.
[Recording of issue.zip](https://github.com/aeoncleanse/Mods/files/528673/Recording.of.issue.zip)

**Comment by aeoncleanse** [comment]
You're not using FAF beta
