### ISSUE TITLE
bal0402 TMD issue

### ISSUE THREAD

**Issue by Exotic-Retard** [aeoncleanse/Mods#204]
put two of these against each other and you will see what i mean.

the TMD on this unit is broken in the way that it still works the old way and tries to shoot it with a low muzzle velocity - set it to the same muzzle vel as per this pr: https://github.com/FAForever/fa/pull/1410

likely a 1line change - MuzzleVelocity = 15,
but you should put in the flare code in anyway because it deserves working tmd as well.

**Comment by aeoncleanse** [comment]
dc06cf07d1cbf2f1743608f622a9db2b3697b307
