### ISSUE TITLE
ACU Overcharges can oneshot another ACU

### ISSUE THREAD

**Issue by Uveso** [aeoncleanse/Mods#208]
I don't know if this is a feature or a bug:

The  damage of overcharge is ~10000 instead of 500, if fired on another ACU
http://forums.faforever.com/viewtopic.php?f=3&t=13430

**Comment by aeoncleanse** [comment]
Please verify this isn't just cos Sera OC upgrades

**Comment by aeoncleanse** [comment]
7a65d12145db0886c30761b48f5ba8276f8feec5
