### ISSUE TITLE
FA Forever lobby no longer listing Black Ops

### ISSUE THREAD

**Issue by RevoluPowered** [aeoncleanse/Mods#209]
Same across multiple clients on different users pc's.
https://drive.google.com/file/d/0BxlTQjnkUieAeU0zQWlDeEMzQXc/view?usp=drivesdk

**Comment by RevoluPowered** [comment]
Not sure if it's an issue at your end or theirs.

**Comment by aeoncleanse** [comment]
Not listing it where? The left? This has been the case since February...

**Comment by RevoluPowered** [comment]
Yeah it's been a while 6+ guys didn't notice that it wasn't listed there anymore haha.

**Comment by RevoluPowered** [comment]
Any ideas why faf doesn't properly support the icons too?

![image](https://cloud.githubusercontent.com/assets/748770/20293797/25537dda-aaf1-11e6-9339-8085985c119d.png)

**Comment by aeoncleanse** [comment]
FAF supports the icons fine. If you're not seeing them, you probably didn't properly download the new init file when FAF updated. Delete programdata/faforever/bin/init_faf.lua and try again.
