### ISSUE TITLE
Goliath / Sera Experimental tank drones not working correctly

### ISSUE THREAD

**Issue by Mushhushshu** [aeoncleanse/Mods#212]
The AA drones on the UEF Goliath and defence drones on the Seraphim EX tank launch and fire but don't move and won't return to carrier. None of the drone related action buttons on the Goliath itself seem to work.

**Comment by aeoncleanse** [comment]
Thanks. The drone code is fucked. I'm gonna have to redesign both these units from scratch. Next patch!
