### ISSUE TITLE
BlackOps acu bugs

### ISSUE THREAD

**Issue by Farmsletje** [aeoncleanse/Mods#214]
First of all: Acu's count as normal units, so OC'ing an acu does 12k dmg (without upgrades).

Aeon:
 - Right arm: 3rd lazer upgrade doesn't fire. 
 - Backpack: All different backpack upgrades provide an aeon tmd, but it is really buggy and almost never works.
 - Backpack: Farsight optics somehow disabled my acu UI. Once i installed the upgrade this window: https://puu.sh/wBxhY/a638684559.png gets replaced by this: https://puu.sh/wBxjH/a31a3a0f9b.jpg

Will edit this if i find more issues.

**Comment by aeoncleanse** [comment]
Don't worry about listing anything further. I expect all these are caused by the same root. Once I find it, we'll do an update

**Comment by aeoncleanse** [comment]
Also, which ACU did you use to fire the OC, and against which?

**Comment by aeoncleanse** [comment]
Have determined patch 3680 is the culprit

**Comment by shalkya** [comment]
just to say the ui you have on the 2nd screenshot look like the one i got when i had the bug with EM v8. 
if it help.

**Comment by aeoncleanse** [comment]
If anyone here is reporting bugs without disabling any and all other mods, I am going to lose it...

**Comment by Farmsletje** [comment]
XD

I only had the 2 BO mods enabled while testing

**Comment by aeoncleanse** [comment]
Still need to know which ACUs you used to test OC

**Comment by aeoncleanse** [comment]
Yeah, still cannot reproduce the OC fail. It works my end.

**Comment by aeoncleanse** [comment]
Test the latest build please. (Just download the zip of develop/blackops)

**Comment by Farmsletje** [comment]
Used the aeon and UEF one.

Replay UID : 6450110

**Comment by aeoncleanse** [comment]
Can't reproduce. We'll make a dedicated issue for this if the V13 doesn't fix it.
