### ISSUE TITLE
UEF Disruptor firing animation glitch

### ISSUE THREAD

**Issue by basdawimp** [aeoncleanse/Mods#224]
If the Attack command is cancelled in between the charge-up and the actual fire the charge-up light effects will continue indefinitely until the full firing sequence is completed.
![uef disruptor firing animation glitch](https://user-images.githubusercontent.com/1522944/29276833-bfcc45e4-8107-11e7-829c-057c5e1db001.png)
[UEF Disruptor firing animation glitch.docx](https://github.com/aeoncleanse/Mods/files/1222552/UEF.Disruptor.firing.animation.glitch.docx) 
-(multiple images in word document)

**Comment by Uveso** [comment]
Fix remark:

Corresponding emiters:
```LUA
Emitter_Muzzle_01
Emitter_Muzzle_02
```

can be fixed by adding a small function inside unit-weapon array (EEL0401_script.lua):
```LUA
            PlayFxWeaponPackSequence = function(self)
                if self.Chargeupeffects then
                    for k, v in self.Chargeupeffects do
                        v:Destroy()
                    end
                    self.Chargeupeffects = {}
                end
                SonicDisruptorWave.PlayFxWeaponPackSequence(self)
            end,
```
