### ISSUE TITLE
attack move button disabled

### ISSUE THREAD

**Issue by PhilipJFryFAF** [aeoncleanse/Mods#227]
none of the BlackOps units (afaik) have the new Attack Move button enabled so you cannot use it

**Comment by Uveso** [comment]
@PhilipJFryFAF:

Can you give me any unitID with a unit that has no Attack Move Button enabled ?

**Comment by PhilipJFryFAF** [comment]
![image](https://user-images.githubusercontent.com/24656673/30013345-483586fe-9146-11e7-80f7-fdce97bfbf8b.png)
ual0001
(didn't even have the acu mod enabled)
i guess the blackops mod breaks that button in some way
![image](https://user-images.githubusercontent.com/24656673/30013389-8e8b8658-9146-11e7-909c-79911b981aad.png)

**Comment by Uveso** [comment]
@PhilipJFryFAF 

I am really sorry, i can't see anything that is causing this inside the mod.
Maybe i am totaly wrong, but is this button working without Black ops ?

If yes, what gameversion you are running ?
I testet FAF over the FAFlobby and develop version.
But this button is always off. (the grey left button right ?)

**Comment by PhilipJFryFAF** [comment]
yes for some reason the button on the left side (attack move) is disabled
you can still (as always) use ALT-rmb to do an attack move but the button in the UI (which was added a few patches ago) appears to be disabled on all units when using BlackOps for some reason
tested with the current stable patch which should be 3686
edit: even without the mod the attack move button is always off
gonna close the issue here and open a new one in the fa repo
