### ISSUE TITLE
Commander is not spawned in Steam version

### ISSUE THREAD

**Issue by qsdoosix** [aeoncleanse/Mods#253]
I'm using a Steam version of Forged Alliance.
Using the BlackOps mod get from FAForever, no other mod is on at the same time. This mod shows up in the mod list, but the commander won't spawn in the start of game, and can't build anything. Please help.

**Comment by Uveso** [comment]
Yes this is right.
The `BlackOpsFAF-Unleashed` version is for the FAF game version (see www.FAForever.com) 

Black Ops is patching many original game files and this makes it incompatible with the steam or vanilla version of the game.
