### ISSUE TITLE
BlackOps ACUs : adjusting the ACUs veterancy gain

### ISSUE THREAD

**Issue by CybranLord** [aeoncleanse/Mods#263]
Hello everyone,
I think there are a problem for the veterancy of the ACUs with this BlackOps ACUs mod. As from FAF patch 3688, the veterancy system has changed to a mass killed system and the ACUs cost were changed to facilitate thier promotions. But for this mod, the ACUs cost stayed the same (it is the same values for all of them) : 
[code]BuildCostEnergy = 5000000,
BuildCostMass = 18000,
BuildRate = 10,
BuildTime = 60000,[/code]

And they need 200% of their mass worth to gain a veterancy level (making it 36k of mass killing to gain one level), making them nearly impossible to promote. 

I am not asking to reduce the price of the ACUs (BlackOps ACUs are still very powerful units so their high costs are still justified for me), I suggest to tone down to 50% of their mass worth (like all non-modded Experimentals) and leaving their cost as they are.

Thanks for reading me.

PS : maybe take a look to their regen gain per veterancy level to be in accord with the new values from patch 3688.

PS 2 : minor issue, but maybe doing the same to the units of the BlackOps mod. If you have the time.

**Comment by Uveso** [comment]
fixed https://github.com/Uveso/BlackOpsFAF-ACUs/commit/f05ce37e8d328fa8fcf364c8e07169f3307269b5
