### ISSUE TITLE
BlackOps V18?

### ISSUE THREAD

**Issue by mikekuzak** [aeoncleanse/Mods#269]
Is this the same code ? There seems to be a mess with BackOps code, versioning and ownership. Is there an official repo, place with the latest upgrades, going in pair with the FAF upgrades ? 

https://forums.faforever.com/viewtopic.php?f=31&t=17161&sid=c6047254aa80b1e06ac295707543f637

**Comment by Uveso** [comment]
@mikekuzak 

You can find the latest (v18) code base here:
https://github.com/Uveso/BlackOpsFAF-ACUs
https://github.com/Uveso/BlackOpsFAF-Unleashed
https://github.com/Uveso/BlackOpsFAF-EXUnits

Also bookmark my main info page on the forum.
(latest versions, backup downloads, GitHub links)
https://forums.faforever.com/viewtopic.php?f=41&t=12416
