### ISSUE TITLE
UEF com - base blackops EEL0001 com does not offer the 3652 auto OC icon (even when you have energy storage)

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#38]
the OC button is available but not the auto OC button from 3652

**Comment by aeoncleanse** [comment]
I can enable Auto-OC now. Perhaps it was another side effect of the fix I just did.

**Comment by aeoncleanse** [comment]
The toggle shows, but OC doesn't actually work.

**Comment by aeoncleanse** [comment]
76d8a6244edd197ea02f371b529ac7ed72e3c721
