### ISSUE TITLE
UEF com - grammer/spelling error for tac missile system

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#39]
![image](https://cloud.githubusercontent.com/assets/16309355/13587290/0e526b3a-e4bf-11e5-8d39-da6fcf8a99cb.png)

**Comment by Nojoke185** [comment]
sexist also - "him" (the ladies may complain!) ;)

**Comment by aeoncleanse** [comment]
f0b2de978ca97526bf692926b09387c5d130a54c
