### ISSUE TITLE
UEF com - Tech 2 improved engineering issues

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#45]
notes say:

adds + 2000 HP (com starts at 12000 after upgrade is at 15000 hp (expected it to be 14000 hp)

adds + 30 regen (com starts with + 10 after upgrade is + 30 (expected it to be + 40)

adds + 20 build speed (com starts with + 10 after upgrade is + 42 (expected it to be + 30)

adds + 3 mass (com starts with + 1 after upgrade is + 13 (expected it to be + 4)

other small issues with further engi updates:

T3 (advanced engineering) has issue with energy not being at expected level (+10 over expected)
T4 (experimental engineering) has issue with build speed being -10 over expected level

**Comment by aeoncleanse** [comment]
753e998ba7538204760b4a56f99296200e0bc188
