### ISSUE TITLE
UEF com - fires at units seemingly within range but guns shells stop short

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#50]
1 - Build a right arm gattling gun
2 - move to a group of enemy, ensure enemy are at edge of range (direct fire range ring - red)

comm engages and fires but shells stop short of target

Same issue seen for next upgrades also:
- build automatic barrel stabilisers
- Enhanced power subsystems

**Comment by aeoncleanse** [comment]
17aad3577da259baac97b0185e144168ae36a2ae
