### ISSUE TITLE
UEF Com - Issues with gattling gun at long rang

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#51]
UEF com

(not sure if these are relevant but I also had T4 apocalyptic engineering and advanced shield battery installed in addition to the below)

1 - upgrade to gattling energy cannon
2 - upgrade to automatic barrel stabilizers
3 - turn on direct fire range ring
4 - walk com so that a group of enemy T1 units are on edge of direct fire range (but just inside) ideally spread about the direct fire ring edge
5 - Com shoots gattling gun at 1st group then stops firing when they are dead - even though live units still remain in range of gattling gun

observations:
Looks like once ACU has hit the first group and killed them, the ACU ignores some of the units in gattling range (but outside of normal gun range)

If a new unit walks into Gattling range, the ACU will fire Gattling gun again - and will sometimes shoot a few of the old units in range, but then will stop firing again leaving units alive and in range

ACU will also seemingly reset if a unit walks into standard gun range and will then engage at full Gattling range for other units (but again will stop after killing them and wait for above triggers again)

May be a limitation of how this works in core code? if so feel free to close!

See screen below where ACU was ignoring engineers and T2 mex which were in range

![image](https://cloud.githubusercontent.com/assets/16309355/13702482/e2656b24-e786-11e5-9d6a-1da32f2ca416.png)

**Comment by aeoncleanse** [comment]
Yeah I don't know how to fix this. It's to do with targeting for the direct fire weapons being set to preferprimaryweapontarget = true. Will leave it open though.

**Comment by aeoncleanse** [comment]
Nojoke185 can you try this out again? I'm hoping the target painter has fixed, or reduced the problem here.

**Comment by Nojoke185** [comment]
using the L3 update - enhanced power subsystems

now getting this when firing weapon:

INFO: Problems loading module '/mods/blackopsacus/projectiles/uefheavyplasmagatlingcannon03/uefheavyplasmagatlingcannon03_script.lua'.  Falling back to 'Projectile' in '/lua/sim/projectile.lua'.
WARNING: ...d alliance\mods\blackopsacus\lua\acusprojectiles.lua(563): access to nonexistent global variable "OmegaOverChargeProjectileTrails"
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
WARNING:         ...d alliance\mods\blackopsacus\lua\acusprojectiles.lua(563): in main chunk
WARNING:         [C]: in function`doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function`import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...ingcannon03\uefheavyplasmagatlingcannon03_script.lua(11): in main chunk
WARNING:         [C]: in function`doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function`import'
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/mods/blackopsacus/lua/acusprojectiles.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function`import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...ingcannon03\uefheavyplasmagatlingcannon03_script.lua(11): in main chunk
WARNING:         [C]: in function`doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function`import'
WARNING: Error importing /mods/blackopsacus/projectiles/uefheavyplasmagatlingcannon03/uefheavyplasmagatlingcannon03_script.lua:
         Error importing '/mods/blackopsacus/projectiles/uefheavyplasmagatlingcannon03/uefheavyplasmagatlingcannon03_script.lua'
         stack traceback:
            [C]: in function `error'
            ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function`import'
INFO: Problems loading module '/mods/blackopsacus/projectiles/uefheavyplasmagatlingcannon03/uefheavyplasmagatlingcannon03_script.lua'.  Falling back to 'Projectile' in '/lua/sim/projectile.lua'.

get similar log spam when firing weapon for Level 1 and Level 2 updates on same path (gattling energy cannon & automatic barrel stabilizers)

I can log this as separate issue if better to track and split from this original issue?

**Comment by aeoncleanse** [comment]
nah thanks for this. Wonder why it didn't show up for me :/

**Comment by aeoncleanse** [comment]
OK try this again, Uveso should have fixed it.

**Comment by Nojoke185** [comment]
seems to have worked from what i can see
