### ISSUE TITLE
Cybran ACU - getting below log on 2nd torp upgrade:

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#55]
WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 1b04fab0: ...e\mods\blackopsacus\units\erl0001\erl0001_script.lua(505): attempt to call method `AddDamageMod' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\erl0001\erl0001_script.lua(505): in function`CreateEnhancement'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(3408): in function `OnWorkEnd'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(80): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:54>

**Comment by Nojoke185** [comment]
getting this on 3rd torp upgrade:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 11ad41b0: ...e\mods\blackopsacus\units\erl0001\erl0001_script.lua(539): attempt to call method `AddDamageMod' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\erl0001\erl0001_script.lua(539): in function`CreateEnhancement'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(3408): in function `OnWorkEnd'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(80): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:54>

**Comment by aeoncleanse** [comment]
c410546bbefa69e964d9738c4494712b3893eb61
