### ISSUE TITLE
Cybran ACU - Level 3 experimental engineering issues

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#56]
following issues observed:

HP - upgrade is meant to add +10000 to existing T2 (at level 17000) - seems to only add 3000 on top of L2 engineering (for total of 20000)

build speed - its meant to add 30 on top of T2 engineering (so 90+30=120) instead sets to just 30

Armour regen - its meant to add 150 on top of T2 engineering (so 115+150=265) instead sets to just 165

oh and the word armor - should this not be armour in all tool tips?

**Comment by aeoncleanse** [comment]
d05634d6946bcacdfc781986f5c8bfdbbc94610d

**Comment by aeoncleanse** [comment]
b7fd871211aaa44063fd8ef4a28c2e8b4ad6f4a4
