### ISSUE TITLE
Cybran ACU - Level 3 experimental engineering issues - point 2

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#57]
upgrading to L3 experimental engineering

com is no longer able to build T2 or T3 factories (only L1)

![image](https://cloud.githubusercontent.com/assets/16309355/14399319/5dc7afbc-fde3-11e5-8daf-c82a1b019516.png)

**Comment by Nojoke185** [comment]
Update - this also applies to the L3 combat engineering upgrade (apocalyptic engineering)

**Comment by Nojoke185** [comment]
Looking at this further, the issue may be more this:

pre-req:
No factories have been built (land/sea/air - applies to all) - only the ACU exists (and hives/paragon!)...
upgrade com to T2 or T3 or T3 experimental

For T2 & T3 ACU you can build T2/T3 factories with com (dependant on tech level)
For T3 experimental you cannot (T2/T3 factories are hidden on build bar - (T1 is available))

compare this to a base ACU - you can only build a T2 or T3 fac with ACU if a factory HQ exists (when the ACU is also at Tech 2/3

Seems the build bar for the blackops ACU is incorrectly making Tech 2/3 factories directly build-able even when no factory HQ exists

**Comment by aeoncleanse** [comment]
This happens for UEF too... :/

**Comment by aeoncleanse** [comment]
82f653ca14cbe7986999820725829bbe9a148051
