### ISSUE TITLE
Cybran ACU - Level 2 Electronic countermeasures issue (maybe?)

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#58]
upgrade L1 electronic enhancment
upgrade L2 Electronic countermeasures

tooltip says:

![image](https://cloud.githubusercontent.com/assets/16309355/14399512/3ac08b04-fde5-11e5-9d0b-eb1f5ff4c9a8.png)

after the upgrade there is no stealth effect field (visual effect as per standard com stealth upgrade)
should this be present?

**Comment by Nojoke185** [comment]
Tested today and seems enemy can see com on radar even when this is enabled
seems stealth does not work

**Comment by aeoncleanse** [comment]
Not sure there should be any visual effect for Stealth, the see-through thing is for Cloaking. Either way, will check next week when I get time again.

**Comment by aeoncleanse** [comment]
0fd749da753e3a4672daffed7d22b48e078b259d

**Comment by Nojoke185** [comment]
stealth now works correct and effect shows on ACU
