### ISSUE TITLE
Cybran ACU - L3 Cloaking subsystems issues

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#59]
Upgrade com to L3 Cloaking subsystems

upgrade should add +50 armour regen - this is not applied

Personal cloaking is installed - but no visual effect given (compare this to standard FA cybran ACU in blackops mod which appears half visible)
screenshot below shows this better (standard com left/blackops com right):

![image](https://cloud.githubusercontent.com/assets/16309355/14399600/302d8ce0-fde6-11e5-8a55-a4c52fa9306c.png)

**Comment by Nojoke185** [comment]
Tested this today vs enemy - ACU cloak does not work (ACU is targeted by enemy when in range and not inside any opponent omni range)

**Comment by aeoncleanse** [comment]
0fd749da753e3a4672daffed7d22b48e078b259d

**Comment by Nojoke185** [comment]
cloaking now works
still missing the +50 armour regen

**Comment by aeoncleanse** [comment]
b2620766925dd82a520be7c11c96296e47bc7502

**Comment by Nojoke185** [comment]
got the 50 regen back :)
