### ISSUE TITLE
Cybran ACU - L2 combat engineering (T3 assault engineering)

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#60]
install T3 assault engineering

armour regen should be adding + 60 (from 30 + 60 = 90) however end result is just 80

**Comment by aeoncleanse** [comment]
This was fixed somewhere. It's fine now

**Comment by Nojoke185** [comment]
seems fine now
looks like the figures have changed somewhere along the line but they all match up now
