### ISSUE TITLE
Cybran ACU - L2 combat engineering (T3 assault engineering) - log issues

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#61]
after upgrade to this, getting below in log:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 228e76f0: ...e\mods\blackopsacus\units\erl0001\erl0001_script.lua(406): attempt to call method `AddDamageMod' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\erl0001\erl0001_script.lua(406): in function`CreateEnhancement'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(3408): in function `OnWorkEnd'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(80): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:54>
WARNING: CLOAK MESH

**Comment by aeoncleanse** [comment]
9cdb9d9e731d06a3e20b741753e9588748ae7fb8

**Comment by Nojoke185** [comment]
working ok - no log error now
