### ISSUE TITLE
Cybran ACU - mazor upgrades (level 1 through level 3)

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#62]
Seems the mazor on the cybran BO ACU is very weak compared to base ACU?
Is it meant to be directly equivalent (to base ACU mazor) or is it by design much weaker?

from a quick test I would guess it is dishing out around 100dps rather than the 1000's in base

**Comment by aeoncleanse** [comment]
By design. The first two are much much weaker. The final stage is approaching the same.
