### ISSUE TITLE
Cybran ACU - overcharge incorrectly enabled

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#63]
when upgrading to engineering suites (left arm)
Overcharge is enabled even when energy storage is only 4000 (5000 required)
applies to both eco and combat engy updates (T2 through experimental)

![image](https://cloud.githubusercontent.com/assets/16309355/14409991/d4632bb4-ff1a-11e5-9c61-11c661ab6e88.png)

**Comment by aeoncleanse** [comment]
bc94bff977a77f26ab2bb701c4e42134bf541a80

**Comment by Nojoke185** [comment]
working as expected
