### ISSUE TITLE
Cybran ACU - combat engineering

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#65]
This upgrade (1st combat engy one - left arm) apparently adds a rocket pack
tried ACU in combat with enemy - no evidence of this weapon being used at all (just standard gun in use)

also noted that the upgrade seems to add an AA laser weapon (this is not mentioned or expected from the tooltip info)

**Comment by aeoncleanse** [comment]
9cdb9d9e731d06a3e20b741753e9588748ae7fb8

**Comment by Nojoke185** [comment]
rocket pack works ok now

still got outstanding comment about the AA laser weapon - this is added on first (tech2) combat engineering upgrade but no mention in the tool tip
ignore this or add something to the tooltip?

**Comment by aeoncleanse** [comment]
37254c83d9b92f9196a8eb05d11f977d8474c4a9

**Comment by Nojoke185** [comment]
no AA weapon on ACU spawn now - fixed
