### ISSUE TITLE
Cybran ACU - emp upgrades (all levels) right arm

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#66]
When you have installed this upgrade (or the higher tier versions of the same) the ACU is able to shoot the EMP weapon whilst building

**Comment by aeoncleanse** [comment]
432cae5e8bc79e4a1690f9f2a8341dc479d449b0

**Comment by Nojoke185** [comment]
Fix not 100% working
with level 1 or level 2 EMP (EMP array & adjusted crystal matrix) installed the ACU still shoots EMP weapon while building
L3 EMP seems to not shoot while building

**Comment by aeoncleanse** [comment]
I tested this working with LVL 1... :/ It was a right pain though.

**Comment by aeoncleanse** [comment]
Hmmm, I can't get the EMP to fire while building. The Rocket pack on the other hand... :/

**Comment by aeoncleanse** [comment]
9dd363384c873fd71b163db41b20fbc8f589627d
