### ISSUE TITLE
Cybran ACU - emp upgrades

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#67]
with any of the right arm EMP upgrades (level 1 to 3) installed the EMP pulse is fired from any direction regardless of way ACU is facing
would expect the ACU to need to turn guns to face target

**Comment by aeoncleanse** [comment]
This is intended. The original idea called for the projectile to actually be invisible, something I hope to do again eventually. They used a horrible method to do it though. So, without warning, areas of target around the ACU will find themselves stunned. Sort of a chaos EMP.
