### ISSUE TITLE
Cybran ACU - Anti Air subsystems (Teleported) back upgrade

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#68]
When you upgrade to teleporter (Anti Air subsystems) it should add the 2 AA lasers (according to the tooltip).

Not sure if they are added or not but when parked under patrolling AI scouts the ACU is not shooting them

**Comment by Nojoke185** [comment]
tested same weapon on back upgrade of armour plating (level 1)
AA lasors work here

**Comment by aeoncleanse** [comment]
Checked at f1272c5b867880b2da1d87ae5010e58354d3f557 - Working fine by this point.
