### ISSUE TITLE
Aeon ACU - log errors on upgrade

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#76]
Not sure if issues or not so logging for review:

seeing lots like this when doing various upgrades:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 1fb74db0: ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(332): attempt to call method `GetBlueprint' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(332): in function`TogglePrimaryGun'
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(656): in function `CreateEnhancement'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(3428): in function`OnWorkEnd'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(80): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:54>
WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 21d55f30: ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(332): attempt to call method `GetBlueprint' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(332): in function`TogglePrimaryGun'
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(688): in function `CreateEnhancement'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(3428): in function`OnWorkEnd'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(80): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:54>

**Comment by aeoncleanse** [comment]
f0a05ed3d1b7c1177b218b77819699e2a53d1fac
