### ISSUE TITLE
Aeon ACU - Quantum maelstrom generator

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#77]
this upgrade should add +5000 hp
nothing is added

also logs below:

WARNING: Failed to create emitter as you passed in an invalid blueprint name /mods/BlackOpsACUs/effects/emitters/maelstrom_aura_01_emit.bp.
WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 1c1636f0: ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(1032): attempt to call method `ScaleEmitter' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(1032): in function`CreateEnhancement'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(3428): in function `OnWorkEnd'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(80): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:54>

**Comment by aeoncleanse** [comment]
8293de05a4d64a3dbaad96dff767214f8c947ffb
