### ISSUE TITLE
Aeon ACU - Farsight optics subsystem

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#78]
upgrade to this
ACU becomes unselectable - UI elements on selection do not show
Log shows below:

WARNING: Error running '/lua/ui/game/gamemain.lua:OnSelectionChanged': ...faforever\bin\fa-release-3652\lua\ui\game\orders.lua(1018): Attempt to set attribute 'behavior' on nil
         stack traceback:
            [C]: in function `error'
            ...alliance\gamedata\mohodata.scd\lua\system\config.lua(12): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:11>
            ...faforever\bin\fa-release-3652\lua\ui\game\orders.lua(1018): in function <...faforever\bin\fa-release-3652\lua\ui\game\orders.lua:1004>
            ...faforever\bin\fa-release-3652\lua\ui\game\orders.lua(1254): in function`SetAvailableOrders'
            ...forever\bin\fa-release-3652\lua\ui\game\gamemain.lua(451): in function <...forever\bin\fa-release-3652\lua\ui\game\gamemain.lua:441>

**Comment by aeoncleanse** [comment]
8d81bad73c875823df6bd17edbd27961b71202e6
