### ISSUE TITLE
Aeon ACU - Combat engineering - 2nd upgrade (assault engineering)

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#79]
Combat engineering - 2nd upgrade (assault engineering)

this should add:
- 8 to chrono dampner range - no range buff is added
- 5000 HP - no HP are added
- 50 regen - not added
- 60 build speed - not added

Log shows:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 1c164230: ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(545): *ERROR: Tried to add a buff that doesn't exist! Name: AEONACUT3BuildRate
         stack traceback:
            [C]: in function `error'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\buff.lua(41): in function`ApplyBuff'
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(545): in function `CreateEnhancement'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(3428): in function`OnWorkEnd'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(80): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:54>

**Comment by aeoncleanse** [comment]
c12dfb5a30c36d1537170778719872f7b41b54ed
