### ISSUE TITLE
Aeon ACU - upgrade issues

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#80]
update ACU to Level 3 combat engineering
(tech 4 apocalyptic engineering)
HP=27500
Regen=310
buildspeed=120
update ACU to quantum maelstrom generator
update ACU to quantum distortion amplifier
HP=40500
Regen=360
buildspeed=120
try to update back to shield battery T2

update fails and log shows:

WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 24e9fcb0: ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(41): *ERROR: Ordered enhancement does not have the proper prereq!
         stack traceback:
            [C]: in function `error'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(2515): in function`OnWorkBegin'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(41): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:33>
WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 21fb32f0: ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(41): *ERROR: Ordered enhancement does not have the proper slot available!
         stack traceback:
            [C]: in function `error'
            ...mdata\faforever\bin\fa-release-3652\lua\sim\unit.lua(2519): in function`OnWorkBegin'
            ...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua(41): in function <...er\bin\fa-release-3652\lua\sim\tasks\enhancetask.lua:33>

**Comment by aeoncleanse** [comment]
e1f15647797a58d13f13473c6c7dd72f915787ba
