### ISSUE TITLE
Aeon ACU - Farsight optics subsystem

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#81]
update to this
try to scry an area
scry doesnt work
log error shows:

WARNING: Error running OnCreate script in CScriptObject at 1b0ad0b0: ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(188): attempt to call method `GetArmyInd' (a nil value)
         stack traceback:
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(188): in function`CreateVisibleEntity'
            ...e\mods\blackopsacus\units\eal0001\eal0001_script.lua(164): in function `OnTargetLocation'
            ...ce\gamedata\lua.scd\lua\sim\tasks\targetlocation.lua(14): in function <...ce\gamedata\lua.scd\lua\sim\tasks\targetlocation.lua:12>

**Comment by aeoncleanse** [comment]
6b52847452e3c46a51add2616f7a8a01979a176a
