### ISSUE TITLE
ANTITELEPORT and SATELLITE are added twice to unitblueprints.

### ISSUE THREAD

**Issue by Uveso** [aeoncleanse/Mods#82]
While debuging some units i found someting out :)

If u are using the mod BlackOpsUnleashed and BlackopsACUs together they will both start a function inside blueprint lua to enter ANTITELEPORT Categorie to all subcommanders and add to all AntiAir Units the TargetRestrictDisallow =  SATELLITE.

But both Mods are adding this, without checking, if the needed string/variable already exist.

Its just a cosmetic issue, but at least we will save some memory :)

Please replace the function in both Blueprints.lua files with the one below. This would be great :)

``` LUA
    local OldModBlueprints = ModBlueprints
    function ModBlueprints(all_blueprints)
        OldModBlueprints(all_blueprints)
        for id,bp in all_blueprints.Unit do
            ExtractCloakMeshBlueprint(bp)
            ExtractPhaseMeshBlueprint(bp)
            if table.find(bp.Categories, 'SUBCOMMANDER') then
                if not table.find(bp.Categories, 'ANTITELEPORT') then
                    table.insert(bp.Categories, 'ANTITELEPORT')
                end
            end
            if bp.Weapon then
                for ik, wep in bp.Weapon do
                    if wep.RangeCategory == 'UWRC_AntiAir' then
                        if not wep.AntiSat == true then
                            if not string.find( wep.TargetRestrictDisallow, 'SATELLITE' ) then
                                wep.TargetRestrictDisallow = wep.TargetRestrictDisallow .. ', SATELLITE'
                            end
                        end
                    end
                end
            end
        end
    end
```

greetings uveso.

**Comment by aeoncleanse** [comment]
Yup this is on my internal list of cleaning up. I plan to have everything I can in the main Unleashed mod, and then only add what's needed in the others.

**Comment by aeoncleanse** [comment]
Looks like I already handled this...
