### ISSUE TITLE
Aeon ACU - HP reset issue

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#83]
update ACU to Level 3 combat engineering
(tech 4 apocalyptic engineering)
HP=27500
Regen=310
buildspeed=120

update ACU to quantum maelstrom generator
update ACU to quantum distortion amplifier
new values:

HP=40500
Regen=360
buildspeed=120

Update back to shield battery T2
Actual new stats are:

HP=35500
Regen=360
buildspeed=120

expected:

HP=27500
Regen=310
buildspeed=120

seems code is dropping the 13000 hp from quantum maelstrom generator & quantum distortion amplifier but is adding the 8000 shield HP to the armour incorrectly (it also adds the 8000 shield separately) result is an 8000 hp buff which is invalid
the 50 regen is also not removed (after destroying quantum distortion amplifier)

**Comment by aeoncleanse** [comment]
86f887d16443ec483dd39b1fe40fd3440e3e6ad7
