### ISSUE TITLE
AI seems to start with no mass/energy

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#85]
noticed in a few sandbox test games the AI gets stuck at the start, very slow to build.
Not 100% sure but if I switch to the AI viewpoint it looks like they are starting with zero mass/energy. This applies to Aeon ACU only (UEF/Cybran are ok)

**Comment by aeoncleanse** [comment]
Should be fixed as of cleanup. Can you check?

**Comment by Nojoke185** [comment]
looks fixed
saw another bug will log seperatly
