### ISSUE TITLE
Intel

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#86]
using latest FA develop branch with latest blackops mod
when scouting enemy they are not visible - only radar return
see screenshot:

![image](https://cloud.githubusercontent.com/assets/16309355/15799765/f377a010-2a5e-11e6-8600-0d04932306bd.png)

**Comment by Nojoke185** [comment]
actually just noticed even my own units seem to be transparent

**Comment by Nojoke185** [comment]
![image](https://cloud.githubusercontent.com/assets/16309355/15799808/100abe5e-2a61-11e6-9f84-051838f1476c.png)

**Comment by Nojoke185** [comment]
this "may" be an issue with FA develop?
was seeing similar problems with base 3654 FA

**Comment by aeoncleanse** [comment]
That's extremely odd. Can you confirm for develop with no mod?

EDIT: Cannot reproduce for either. Do you have a log for this game, or for one where you have it happen?

**Comment by Nojoke185** [comment]
just trying this again now and not seeing the problem any more
dont understand what caused it and dont have a log either sorry

1st time I saw it was with 3654 (develop) and blackops (<<< latest for both) - no other mods
2nd time I saw it was in base 3654 (develop) - no other mods (tried it after blackops game to check)

issue no longer apparent
suggest close this and if it can be recreated it can be dealt with then?

N

**Comment by aeoncleanse** [comment]
Agreed
