### ISSUE TITLE
BSL0401 energy being don't spawns when reclaimed

### ISSUE THREAD

**Issue by Uveso** [aeoncleanse/Mods#87]
Like the XSL0401 (Ythotha), the BSL0401 (Experimental Hover Tank) has an energy spirit.
Mabye it makes sense that the Hovertank Spirit also spawns on reclaim ?

(I also changed the spirit in Total Mayhem, Experimental Wars and XtremWars)

**Comment by aeoncleanse** [comment]
933c73e541fad98e21b3f36b371930a4ca1b6dd6
