### ISSUE TITLE
hydrocarbon plants have no pause option on upgrade

### ISSUE THREAD

**Issue by PlaYsiA** [aeoncleanse/Mods#88]
Blackops tested on 27/06/16

As title suggests, when I am upgrading a hydrocarbon plant there was no option to pause like there is when upgrading mexes and so on. (was testing as Aeon)

**Comment by Uveso** [comment]
@PlaYsiA 
Thanks for the hint! You are right, Hydros should have pause like massextractors etc.

**Comment by Uveso** [comment]
Fixed and merged. Can be closed.
