### ISSUE TITLE
All Units of Aeon & Seraphim Cloaking 24/7

### ISSUE THREAD

**Issue by ZephyrWarrior** [aeoncleanse/Mods#89]
In the ACU portion of the mod (I disabled to find the issue via process of elimination), there is a bug causing the ACU (Images 1 & 2) and all units on the team (Image 3) to be cloaked as long as the ACU is alive. This issue only occurs in Aeon and Seraphim players (Images 1 & 2), and seems to (in many cases) extend to team mates' units as well. It is unknown if the cloaking is an active effect or a purely visual one. The Aeon commander, although cloaked, seems to have the artillery upgrade affixed at spawn (Image 2), and the model does not appear to update when upgrades are applied. The Seraphim commander also appears to have upgrades affixed at spawn (Image 1), but neither Aeon nor Seraphim commanders use the abilities indicated by their visual alterations. Upon the commander's death, all remaining units do de-cloak (Images 4 & 5). This issue does not affect Cybran or UEF commanders.

![1) cloaked seraphim commander with upgrades](https://cloud.githubusercontent.com/assets/9412560/16558672/6a72d908-41a4-11e6-93cf-b2d1b29a482e.png)
![2) cloaked aeon commander with artillery](https://cloud.githubusercontent.com/assets/9412560/16558681/6f292cc2-41a4-11e6-8631-1f031f1e6b1e.png)
![3) cloaked freshly built pgen](https://cloud.githubusercontent.com/assets/9412560/16558682/6f426480-41a4-11e6-9fb4-a082142b4b77.png)
![4) commander destruction](https://cloud.githubusercontent.com/assets/9412560/16558694/894001bc-41a4-11e6-84c9-14f35dfb771f.png)
![5) de-cloaked pgen](https://cloud.githubusercontent.com/assets/9412560/16558685/6f58cc16-41a4-11e6-938e-f57da9a57792.png)

**Comment by AndroTritium** [comment]
I have been affected by the same issue, under the same circumstances. I can confirm that it only affects Aeon and Seraphim.

**Comment by ZephyrWarrior** [comment]
The effect does in fact have a range, with a massive AOE. This is my friend's Cybran base in the south while I'm at the north and you can see the effect in action.

![cloak range](https://cloud.githubusercontent.com/assets/9412560/16559008/fdef8f76-41a6-11e6-8ca0-04857ba31a09.png)

**Comment by aeoncleanse** [comment]
Well, the Seraphim isn't ready yet, so my fixes for that may fix this. I'll keep it open, but I must also say I've not yet seen this occur...

**Comment by aeoncleanse** [comment]
Fixed in latest push

**Comment by ZephyrWarrior** [comment]
Seraphim units and structures are still cloaked as previously mentioned, if you're waiting on the faction to be ready that's all good. Aeon does appear to be fixed.

Unfortunately now the commanders all spawn invisible. I recall this being an issue when I was using a mismatched version, is this updated for 3654? 

P.S. Would it be possible to have a SupComVersion.txt file in the root to let us know what version the current release is compatible with (if it is in one of the info files I must be blind and I apologize)?

**Comment by aeoncleanse** [comment]
Try it again. Remember to use game logs to try and narrow issues down if you have time.

This is compatible with FAF. Latest FAF.

**Comment by ZephyrWarrior** [comment]
Looks like we're good! Sera ACU still has visual upgrades installed but that's not important and will be fixed in your Sera work no doubt. Thanks for looking into this. :)

**Comment by Nojoke185** [comment]
so just to check..what should happen with SERA ACU with cloaking subsystems?
if i update to this the ACU and nearby units are cloaked (when it is active)
the enhancement description only mentions cloaking the ACU and not surrounding structures/units

**Comment by aeoncleanse** [comment]
I'll update the description.
