### ISSUE TITLE
T1 Tankhunter needs another look.

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#91]
I think lock mode is reversed on the icon. Transfers seem slow. And asking to move immediately after un-locking it makes it move without animating.

**Comment by PlaYsiA** [comment]
I made a replay demonstrating it.

If the unit has a moveorder while it gets locked he doesn't shoot.
[blackopst1pdmobilebug.zip](https://github.com/aeoncleanse/Mods/files/355582/blackopst1pdmobilebug.zip)

**Comment by aeoncleanse** [comment]
4cb5ac8de768e38deb4f5ee054e7efc6f072d90a
