### ISSUE TITLE
Seraphim ACU spawns with full enhacment graphics

### ISSUE THREAD

**Issue by Uveso** [aeoncleanse/Mods#94]
Seraphim has all enhancement graphics activated at start:
![seraacu](https://cloud.githubusercontent.com/assets/17804547/16710447/f21bbe36-462e-11e6-9853-4b4eed758714.png)

**Comment by lhigginbotham** [comment]
I'm seeing the same thing with the Aeon ACU as well.

**Comment by aeoncleanse** [comment]
Ooooh, all the bones huh. Interesting. Thanks guys :)

**Comment by Uveso** [comment]
but at least it looks awesome :D

**Comment by aeoncleanse** [comment]
Even odder, this ONLY happens at game start, not if one spawns the unit normally...

**Comment by aeoncleanse** [comment]
faa7f939fa5a962eb27245c168224fd961a872fb
